-- DTS 201 MCQ Questions from Quiz Files + Converted Q&A
-- Course ID: 203ee6ac-e5c8-4644-bb3c-855884ba8de4
-- Deduplicating against existing 30 questions

INSERT INTO quiz_questions (course_id, question, options, correct_answer, explanation) VALUES

-- ===== FROM QUIZ 1 (DataScienceQuiz_1.pdf) =====

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What does an R-squared value of 0.85 mean?',
'["The model has an error of 15%", "85% of the predictions are correct", "The model is 85% better than a random guess", "85% of the variance in the target variable is explained by the model"]',
3,
'R-squared (R²) measures how well the model''s independent variables explain the variability in the dependent/target variable. An R² of 0.85 means the model accounts for 85% of the variance.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'How does CRISP-DM help manage project risk?',
'["By focusing only on the modeling phase", "By forcing a sequential, waterfall approach", "By ignoring the business context", "By ensuring thorough understanding and iterative development"]',
3,
'CRISP-DM manages risk by starting with deep business and data understanding before any modeling begins, and by allowing teams to loop back and course-correct at any phase.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'If during the Modeling phase you realize you need to integrate data from a new source, you would go back to which phase?',
'["Business Understanding", "Data Understanding", "Evaluation", "Data Preparation"]',
3,
'Integrating data from a new source is a Data Preparation task — specifically the ''integrate data'' sub-task where data from multiple sources is merged.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'Scaling data to have a mean of 0 and a standard deviation of 1 is called:',
'["Min-Max Normalization", "Data Integration", "Standardization (or Z-score normalization)", "Data Reduction"]',
2,
'Standardization transforms data so that it has a mean of 0 and a standard deviation of 1, using the formula z = (x − μ) / σ.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'If findings in the Modeling phase reveal a need for a new derived feature, you would loop back to which phase?',
'["Business Understanding", "Data Understanding", "Data Preparation", "Evaluation"]',
2,
'Creating a new derived feature is exactly the ''construct data'' task within Data Preparation. You would loop back there to engineer the new attribute before resuming modeling.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is the key difference between batch processing and stream processing?',
'["Batch processing is slower than stream processing", "Batch processes data in chunks at intervals, while stream processes data continuously in real-time", "Batch processing is for structured data only", "Stream processing is for unstructured data only"]',
1,
'Batch processing collects data over a period and processes it all at once (e.g. nightly payroll runs), while stream processing handles each data event as it arrives with minimal latency.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'A model is successfully deployed, but after six months, its predictions become less accurate. This situation is addressed in which part of CRISP-DM?',
'["The initial Business Understanding phase", "The Modeling phase", "The monitoring and maintenance plan from the Deployment phase", "The Data Understanding phase"]',
2,
'This describes data drift — a model degrading over time. The Deployment phase explicitly includes a monitoring and maintenance plan to detect and respond to this.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What does CRISP-DM stand for?',
'["Cross-Industry Standard Process for Data Mining", "Cross-Integrated System for Data Modeling", "Comprehensive Research in Statistical Programming for Data Management", "Crisp Data Mining"]',
0,
'CRISP-DM stands for Cross-Industry Standard Process for Data Mining — its full, official name.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is a zettabyte?',
'["A billion gigabytes", "A million terabytes", "A thousand petabytes", "A trillion megabytes"]',
1,
'A zettabyte equals approximately one million terabytes. Precisely: 1 ZB = 1,000 EB = 1,000,000 PB = 1,000,000,000 TB.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'Which phase involves creating the final dataset that will be used for modeling?',
'["Data Preparation", "Business Understanding", "Modeling", "Data Understanding"]',
0,
'The entire purpose of the Data Preparation phase is to produce the final, clean, structured dataset that gets fed into the Modeling phase.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'Which of the following best describes in-memory computing?',
'["Processing data streams in real-time", "Storing data in RAM for faster processing speeds", "Processing data in batches", "Storing data on a hard drive for long-term persistence"]',
1,
'In-memory computing keeps data in RAM rather than reading from disk, dramatically reducing latency. Apache Spark is a prime example.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'Which V of Big Data refers to the different forms of data, including structured, unstructured, and semi-structured?',
'["Variety", "Volume", "Veracity", "Value"]',
0,
'Variety refers to the different types and formats data can come in — structured, unstructured, and semi-structured.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is a pilot deployment?',
'["Deploying the model without any planning", "A small-scale implementation of the model to test its performance", "A type of model evaluation metric", "The final, full-scale launch of the model"]',
1,
'A pilot deployment is a controlled, limited rollout done before full production release to validate real-world performance.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'Which metric is most sensitive to false negatives?',
'["Recall", "Precision", "Accuracy", "Specificity"]',
0,
'Recall = TP / (TP + FN). False negatives sit directly in the denominator, so as false negatives increase, recall decreases.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'Which of the following is NOT a typical task in the Data Preparation phase?',
'["Data formatting", "Data cleaning", "Data integration", "Defining business success criteria"]',
3,
'Defining business success criteria belongs to the Business Understanding phase, not Data Preparation.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'Predicting the price of a used car based on its age, mileage, and brand is a:',
'["Reinforcement learning problem", "Classification problem", "Clustering problem", "Regression problem"]',
3,
'Predicting a continuous numerical value (price) from input features is the definition of regression.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'Which type of data is best suited for analysis using a relational database?',
'["Unstructured data", "Semi-structured data", "All of the above", "Structured data"]',
3,
'Relational databases are built around tables with rows, columns, and defined schemas — perfectly suited for structured data.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'In the bias-variance tradeoff, increasing model complexity typically leads to:',
'["Decreased bias, increased variance", "Increased bias, increased variance", "Decreased bias, decreased variance", "Increased bias, decreased variance"]',
0,
'As model complexity increases, the model fits training data more closely — reducing bias but increasing variance (more sensitive to noise).'),

-- ===== FROM QUIZ 2 (DataScienceQuiz-2.pdf) =====

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'The iterative nature of CRISP-DM means that:',
'["Findings in a later phase can cause you to revisit earlier phases", "The process must be repeated exactly six times", "The project can only move forward, never backward", "Only the Modeling phase is iterative"]',
0,
'CRISP-DM is explicitly designed to be non-linear and iterative. Discovering something during the Modeling phase might send you back to Data Preparation or even Business Understanding.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'Splitting a large dataset horizontally across multiple databases is known as:',
'["Indexing", "Replication", "Clustering", "Sharding"]',
3,
'Sharding is the technique of splitting a large dataset horizontally (by rows) across multiple databases or nodes.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'Principal Component Analysis (PCA) is a technique for:',
'["Regression", "Dimensionality Reduction", "Feature Engineering", "Classification"]',
1,
'PCA transforms high-dimensional data into a smaller set of uncorrelated components that still capture the most variance in the data.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'Which CRISP-DM phase involves tasks like plan deployment and plan monitoring and maintenance?',
'["Evaluation", "Deployment", "Modeling", "Data Preparation"]',
1,
'In CRISP-DM, the Deployment phase is where you plan how the model will be put into production, including planning for ongoing monitoring and maintenance.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'The process of choosing the most relevant features for model building is called:',
'["Feature Engineering", "Model Evaluation", "Feature Selection", "Data Transformation"]',
2,
'Feature Selection is specifically the process of identifying and keeping only the most relevant input variables for your model.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is the purpose of data reduction?',
'["To increase the size of the dataset", "To clean the data", "To obtain a smaller, representative dataset that produces similar analytical results", "To add more features to the data"]',
2,
'Data reduction aims to shrink the volume of data while preserving the integrity of the analysis — making processing faster and more efficient.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is Apache Kafka primarily used for?',
'["Real-time data streaming and integration", "Distributed file storage", "Building machine learning models", "Batch processing"]',
0,
'Apache Kafka is a distributed event streaming platform designed to handle high-throughput, low-latency data pipelines.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is the main goal of unsupervised learning?',
'["To find hidden patterns or groupings in unlabeled data", "To predict a labeled target variable", "To improve model accuracy", "To maximize rewards in an environment"]',
0,
'Unsupervised learning works with data that has no predefined labels, discovering structure on its own — think clustering, dimensionality reduction, or association rules.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'The main activity of the Data Understanding phase is:',
'["Creating a project plan", "Deploying the model", "Getting familiar with the data and identifying quality issues", "Building machine learning models"]',
2,
'In CRISP-DM, the Data Understanding phase involves collecting data, exploring it through descriptive statistics and visualization, and flagging quality problems.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'A decision tree that grows very deep and has many branches is likely suffering from:',
'["Overfitting", "High bias", "Low variance", "Underfitting"]',
0,
'A very deep decision tree has essentially memorized the training data — it captures noise and outliers rather than the underlying pattern.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'During the Evaluation phase, the model performance is assessed against:',
'["The Business Success Criteria", "The project timeline", "The technical benchmarks", "The data volume"]',
0,
'In CRISP-DM''s Evaluation phase, the key question is whether the model meets the business objectives set out at the start.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'A recommendation engine that suggests what movies to watch next is an example of:',
'["Descriptive Analytics", "Predictive Analytics", "Prescriptive Analytics", "Diagnostic Analytics"]',
2,
'A recommendation engine actively recommends an action (watch this movie). That is the hallmark of prescriptive analytics.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'The CRISP-DM methodology is best described as:',
'["A standard process model for data mining", "A data visualization technique", "A proprietary algorithm", "A type of database"]',
0,
'CRISP-DM is an industry-neutral, standardized framework that guides data mining projects through six phases.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What does a final report in the Deployment phase typically include?',
'["The raw data used for the project", "A summary of the entire project, findings, and how they will be used", "Only the model code", "A list of all data quality issues"]',
1,
'The final report is a comprehensive document meant to communicate the full story — what was done, what was found, and how results will be applied.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'The determine next steps task in the Evaluation phase could lead to:',
'["Only terminating the project", "Only proceeding to deployment", "Starting the project over from the beginning", "Either proceeding to deployment or iterating for improvement"]',
3,
'Due to CRISP-DM''s iterative nature, if the model meets criteria you proceed to deployment; if not, you loop back to improve.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'Which phase is often the most time-consuming in a data science project?',
'["Data Preparation", "Modeling", "Business Understanding", "Evaluation"]',
0,
'Data preparation (cleaning, transforming, integrating, formatting) consumes roughly 60-80% of a data scientist''s time.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What does the construct data task in Data Preparation involve?',
'["Combining data from multiple sources", "Deleting unwanted records", "Checking for data quality issues", "Creating new derived attributes from existing ones"]',
3,
'In CRISP-DM, construct data specifically refers to generating new features derived from existing data.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'Which of the following best describes a data warehouse?',
'["A repository for raw, unprocessed data in its native format", "A centralized repository for structured, processed data optimized for analysis", "A type of NoSQL database", "A system for processing real-time data streams"]',
1,
'A data warehouse stores cleaned, transformed, and integrated data from multiple sources, specifically designed for querying, reporting, and business intelligence.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'Selecting data, cleaning data, and constructing new attributes are all tasks in the:',
'["Deployment phase", "Data Preparation phase", "Modeling phase", "Data Understanding phase"]',
1,
'All three tasks are core activities explicitly defined within CRISP-DM''s Data Preparation phase.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'Market basket analysis, which finds items frequently bought together, is an example of:',
'["Association Rule Mining", "Regression", "Classification", "Clustering"]',
0,
'Market basket analysis is the textbook use case for association rule mining — discovering relationships between items.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'Which type of data is self-describing and often uses tags to separate data elements, like XML or JSON?',
'["Semi-structured", "Structured", "Unstructured", "Quantitative"]',
0,
'Semi-structured data uses tags, keys, or markers to self-describe and organize its elements, unlike rigid table structures or completely raw data.'),

-- ===== FROM QUIZ 3 (DataScience_Quiz_3.pdf) =====

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'A non-parametric model is characterized by:',
'["A fixed number of parameters regardless of data size", "Requiring less data to train", "Not making strong assumptions about the form of the mapping function", "Always being simpler than parametric models"]',
2,
'Non-parametric models do not assume a specific functional form for the data, letting the data determine the structure.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'Which of the following is NOT a phase in CRISP-DM?',
'["Deployment", "Data Preparation", "Data Visualization", "Business Understanding"]',
2,
'Data Visualization is NOT a phase. The six phases are: Business Understanding, Data Understanding, Data Preparation, Modeling, Evaluation, and Deployment.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'Neo4j is a popular example of which type of database?',
'["Graph", "Relational", "Document", "Column-Family"]',
0,
'Neo4j is the most well-known graph database. It stores data as nodes and relationships (edges), ideal for complex connected data like social networks.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'Unsupervised learning is used when the data:',
'["Has clear input and output labels", "Is always numerical", "Requires an agent to interact with an environment", "Has no labels and the goal is to find hidden patterns"]',
3,
'Unsupervised learning works with unlabeled data. The goal is to discover hidden structure, clusters, or patterns without predefined output labels.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is a key output of the Data Understanding phase?',
'["An initial data quality report", "A list of business success criteria", "A deployed model", "A set of model parameters"]',
0,
'During Data Understanding, data is collected, explored, and assessed. A key output is an initial data quality report identifying issues like missing values and outliers.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is the main difference between interval and ratio data?',
'["There is no difference", "Interval data has order, ratio data does not", "Interval data has a true zero, ratio data does not", "Ratio data has a true zero, interval data does not"]',
3,
'Ratio data (e.g., weight, height) has a meaningful zero meaning none, while interval data (e.g., temperature in Celsius) does not — 0°C does not mean no temperature.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'A professional who builds and maintains the infrastructure for data generation, storage, and processing is a:',
'["Business Analyst", "Data Analyst", "Data Engineer", "Data Scientist"]',
2,
'Data Engineers build and maintain the pipelines, databases, and infrastructure that enable data generation, storage, and processing.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'The CAP theorem states that a distributed system can only guarantee two of three properties. Which are they?',
'["Cost, Availability, Performance", "Capacity, Access, Protocol", "Consistency, Availability, Partition Tolerance", "Computing, Analytics, Processing"]',
2,
'The CAP theorem states a distributed system can only guarantee two of: Consistency, Availability, and Partition Tolerance.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'Which of the following is an example of structured data?',
'["A video file", "An email body", "A social media post", "A relational database table"]',
3,
'Structured data is organized in a predefined schema with rows and columns, exactly as in a relational database table.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'Which NoSQL database type is best suited for representing and querying relationships between entities?',
'["Graph Database", "Key-Value Store", "Column-Family Store", "Document Database"]',
0,
'Graph databases are purpose-built for storing and querying relationships between entities using nodes and edges.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'Why is data visualization crucial in data science?',
'["It helps in identifying patterns, trends, and outliers", "It makes the data look more attractive", "It is only used for final presentations", "It replaces the need for statistical analysis"]',
0,
'Data visualization allows analysts to quickly identify patterns, trends, and anomalies that would be difficult to detect by examining raw numbers alone.'),

-- ===== CONVERTED FROM Q&A FILE =====

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is the difference between data and information?',
'["Data and information are the same thing", "Data is processed information", "Data is raw facts without context; information is data that has been processed and given meaning", "Information is always numerical while data is textual"]',
2,
'Data are raw, unprocessed facts and figures without context (e.g., 25). Information is data that has been processed, organized, and given context to make it meaningful (e.g., The customer is 25 years old).'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What are the two primary components of a dataset?',
'["Tables and queries", "Entities (rows/observations) and attributes (columns/features)", "Headers and footers", "Inputs and outputs"]',
1,
'A dataset''s two primary components are entities (rows/observations) and attributes (columns/features/variables).'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is the difference between structured and unstructured data?',
'["Structured data is larger than unstructured data", "Structured data has a predefined format; unstructured data has no predefined organization", "Unstructured data is always textual", "There is no difference"]',
1,
'Structured data has a predefined format and resides in fixed fields (like tables). Unstructured data has no predefined format or organization.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is nominal data?',
'["Data with a meaningful order between categories", "Categorical data with no inherent order or ranking", "Numerical data with equal intervals", "Data with a true zero point"]',
1,
'Nominal data is categorical data with no inherent order or ranking. Arithmetic operations are meaningless. Example: Hair color, Gender.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is ordinal data?',
'["Data with no order or ranking", "Numerical data that can be measured precisely", "Categorical data with a clear order but unequal intervals between values", "Data with a true zero point allowing ratio comparisons"]',
2,
'Ordinal data has a clear, meaningful order, but the intervals between values are not known or equal. Example: Education level (High School, Bachelor''s, Master''s, PhD).'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is a discrete variable?',
'["A variable that can take any value in a range", "A variable whose values are countable and typically integers", "A variable that is always categorical", "A variable with no defined range"]',
1,
'A discrete variable is one whose values are countable and typically integers. Example: Number of children in a family.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'Why is data preprocessing necessary?',
'["It makes data smaller", "Real-world data is often incomplete and inconsistent, which can lead to inaccurate models", "It is only needed for Big Data", "It replaces the need for modeling"]',
1,
'Data preprocessing transforms raw data into a clean format. Real-world data is often incomplete, inconsistent, and lacking in certain behaviors or trends.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What are two common strategies for handling missing data?',
'["Ignore the dataset entirely or collect new data", "Remove records with missing values or impute using mean/median/mode", "Always delete the column or duplicate the rows", "Replace with zeros or use random values"]',
1,
'Two common strategies: 1) Remove records with missing values, 2) Impute missing values using the mean, median, or mode of the column.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is data integration?',
'["The process of visualizing data", "Combining data from different sources into a single unified view", "Reducing the size of a dataset", "Converting data types"]',
1,
'Data integration is the process of combining data from different sources into a single, unified view. A primary challenge is entity identification.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is the difference between a data warehouse and a data lake?',
'["They are the same thing", "A data warehouse stores processed structured data; a data lake stores raw data in its native format", "A data lake is smaller than a data warehouse", "A data warehouse uses NoSQL; a data lake uses SQL"]',
1,
'A data warehouse stores processed, structured data (schema-on-write). A data lake stores vast amounts of raw data in its native format (schema-on-read).'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is a primary key in a relational database?',
'["Any column in a table", "A column that links two tables together", "A column that uniquely identifies each row in a table", "A column that allows NULL values"]',
2,
'A primary key is a specific column that uniquely identifies each row in the table. It must contain unique values and cannot contain NULL values.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is the purpose of SQL?',
'["To create web applications", "To manage and manipulate relational databases", "To design user interfaces", "To process images"]',
1,
'SQL (Structured Query Language) is designed for managing and manipulating relational databases — querying, inserting, updating, and deleting data.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What does Big Data refer to?',
'["Any data stored in a computer", "Data that fits in a single spreadsheet", "Extremely large and complex datasets that cannot be easily managed with traditional tools", "Data that is only numerical"]',
2,
'Big Data refers to extremely large and complex datasets that cannot be easily managed, processed, or analyzed with traditional data processing tools.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What are the three original Vs of Big Data?',
'["Value, Veracity, Variability", "Volume, Velocity, Variety", "Vision, Validation, Verification", "Virtualization, Visualization, Velocity"]',
1,
'The three original Vs: 1) Volume — the sheer scale of data, 2) Velocity — the speed of data generation, 3) Variety — different types of data.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is the Veracity V in Big Data?',
'["The speed of data generation", "The different types of data", "The quality and trustworthiness of the data", "The business value derived from data"]',
2,
'Veracity refers to the quality and trustworthiness of the data. Big Data often comes from multiple sources and can be noisy, messy, or inconsistent.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'Why is Value considered the most important V of Big Data?',
'["Because it determines data size", "Because without extracting meaningful insights, data and processing efforts are useless", "Because it measures data speed", "Because it ensures data accuracy"]',
1,
'Value refers to turning data into something useful for the organization. If meaningful insights cannot be extracted, the data efforts are essentially useless.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is Apache Hadoop?',
'["A programming language", "An open-source framework for distributed storage and processing of large datasets", "A type of database", "A data visualization tool"]',
1,
'Apache Hadoop is an open-source framework for distributed storage and processing across clusters. Its two core components are HDFS (storage) and MapReduce (processing).'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is the purpose of the Hadoop Distributed File System (HDFS)?',
'["To process data in real-time", "To store massive amounts of data reliably across many machines", "To build machine learning models", "To manage database queries"]',
1,
'HDFS stores massive amounts of data reliably across many machines by breaking files into large blocks and replicating them across multiple nodes.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'How is Apache Spark different from Hadoop MapReduce?',
'["Spark uses disk-based processing while MapReduce uses RAM", "Spark uses in-memory computing, making it significantly faster", "Spark can only handle structured data", "There is no difference"]',
1,
'Apache Spark uses in-memory computing, making it significantly faster than Hadoop MapReduce, especially for iterative algorithms like machine learning.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'Why did NoSQL databases emerge?',
'["To replace all relational databases", "To handle large volumes of unstructured and rapidly changing data with more flexibility", "To make data smaller", "To standardize all data formats"]',
1,
'NoSQL databases emerged to handle large volumes of unstructured, semi-structured, or rapidly changing data, offering more flexibility and scalability than traditional relational databases.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is the difference between a Data Scientist and a Data Analyst?',
'["They have the same role", "A Data Analyst focuses on descriptive analytics; a Data Scientist focuses on predictive and prescriptive analytics", "A Data Scientist only creates visualizations", "A Data Analyst builds machine learning models"]',
1,
'A Data Analyst focuses on descriptive analytics and reports. A Data Scientist focuses on predictive and prescriptive analytics, building complex models.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is Machine Learning?',
'["A type of database", "A subset of AI that allows systems to learn from experience without explicit programming", "A data visualization technique", "A hardware component"]',
1,
'Machine Learning is a subset of AI that provides systems the ability to automatically learn and improve from experience without being explicitly programmed.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What are the three main types of machine learning?',
'["Classification, Regression, Clustering", "Supervised, Unsupervised, and Reinforcement Learning", "Training, Testing, Validation", "Descriptive, Predictive, Prescriptive"]',
1,
'The three main types are: 1) Supervised Learning, 2) Unsupervised Learning, and 3) Reinforcement Learning.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is the difference between a feature and a label in supervised learning?',
'["Features are outputs; labels are inputs", "A feature is an input variable; a label is the target variable the model predicts", "They are the same thing", "Features are always categorical; labels are always numerical"]',
1,
'A feature is an individual measurable property (the input variable). A label is the target variable the model is trying to predict (the output).'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'Why is it important to keep test data separate from training data?',
'["To save storage space", "To get an unbiased estimate of how well the model performs on new data", "Test data is not actually needed", "To make training faster"]',
1,
'Keeping test data separate provides an unbiased estimate of how well the model will perform on new, real-world data.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is overfitting?',
'["When a model is too simple to capture patterns", "When a model performs well on both training and test data", "When a model learns training data too well including noise, performing poorly on unseen data", "When a model has too few features"]',
2,
'Overfitting occurs when a model learns the training data too well, including noise and random fluctuations, failing to generalize to new data.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is a classification problem?',
'["Predicting a continuous numerical value", "Grouping similar data points together", "Predicting a category or class label", "Finding associations between items"]',
2,
'A classification problem is a type of supervised learning where the output variable is a category or class. Example: Classifying emails as spam or not spam.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is clustering?',
'["Predicting a specific target variable", "Grouping similar data points together based on their features", "A type of supervised learning", "Splitting data across multiple databases"]',
1,
'Clustering is an unsupervised learning technique that groups similar data points together. Example: Grouping customers into segments based on purchasing history.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is Accuracy as a performance metric?',
'["The ratio of true positives to predicted positives", "The ratio of correctly predicted observations to total observations", "The harmonic mean of precision and recall", "The area under the ROC curve"]',
1,
'Accuracy is the ratio of correctly predicted observations to total observations. Formula: (TP + TN) / (TP + TN + FP + FN).'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is the F1-score?',
'["The sum of precision and recall", "The difference between true positives and false negatives", "The harmonic mean of Precision and Recall", "The ratio of correct predictions to total predictions"]',
2,
'The F1-score is the harmonic mean of Precision and Recall, providing a single score that balances both concerns.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What does an ROC curve show?',
'["The training time of a model", "The True Positive Rate vs False Positive Rate at all classification thresholds", "The loss function over training epochs", "The data distribution"]',
1,
'An ROC curve plots the True Positive Rate against the False Positive Rate. AUC represents the degree of separability between classes.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is Mean Squared Error (MSE)?',
'["The average of all predicted values", "The average squared difference between predicted and actual values", "The number of incorrect predictions", "The variance of the training data"]',
1,
'MSE measures the average squared difference between predicted values and actual values. Lower values indicate a better fit.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is bias in a machine learning model?',
'["The error from the model''s sensitivity to noise in training data", "The error from approximating a complex problem with a simpler model", "The total error of the model", "The variance in predictions"]',
1,
'Bias is the error introduced by approximating a real-world problem with a simpler model. High bias can cause underfitting.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is variance in a machine learning model?',
'["The error from oversimplifying the model", "The total number of features used", "The error from the model''s sensitivity to small fluctuations in training data", "The average prediction value"]',
2,
'Variance is the error from the model''s sensitivity to small fluctuations in the training data. High variance can cause overfitting.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is cross-validation?',
'["Training a model on all available data", "Evaluating models by training on subsets and testing on complementary subsets", "Removing outliers from the dataset", "A type of feature selection"]',
1,
'Cross-validation evaluates models by training on subsets of data and evaluating on the complementary subset. K-fold divides data into k equal folds.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is the difference between a hyperparameter and a model parameter?',
'["They are the same thing", "A hyperparameter is set before training; a model parameter is learned from the data during training", "A model parameter is set manually; a hyperparameter is learned automatically", "Hyperparameters only exist in neural networks"]',
1,
'A hyperparameter is a configuration set before training (e.g., learning rate). A model parameter is learned from data during training (e.g., coefficients).'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'How many phases are there in the CRISP-DM model?',
'["4 phases", "5 phases", "6 phases", "8 phases"]',
2,
'There are 6 phases: Business Understanding, Data Understanding, Data Preparation, Modeling, Evaluation, and Deployment.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is the main goal of the Business Understanding phase?',
'["To build the best model possible", "To understand project objectives from a business perspective and convert them into a data mining problem", "To clean and prepare the data", "To deploy the final model"]',
1,
'The goal is to understand the project objectives and requirements from a business perspective, then convert this into a data mining problem definition.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is the main goal of the Evaluation phase in CRISP-DM?',
'["To build and tune models", "To assess whether the model meets business success criteria", "To prepare the data for modeling", "To deploy the model into production"]',
1,
'The Evaluation phase assesses the model in the context of business objectives and determines if it is good enough for deployment.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is the main goal of the Deployment phase?',
'["To train the model", "To evaluate technical metrics", "To put the model and its insights into production use", "To collect initial data"]',
2,
'The Deployment phase puts the model into production use within the organization''s environment — generating reports, integrating into applications, etc.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is data drift?',
'["Moving data to a new server", "The change in statistical properties of model input data over time", "A type of data cleaning", "The speed of data generation"]',
1,
'Data drift is the change in statistical properties of the model''s input data over time. It requires the model to be retrained or updated.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'Is CRISP-DM only applicable to Big Data projects?',
'["Yes, it was designed only for Big Data", "No, it works regardless of data size", "Yes, it requires distributed computing", "No, but it only works with structured data"]',
1,
'CRISP-DM is a process model for data mining and works regardless of data size. The core tasks are essential whether working with a small file or a massive cluster.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is data replication in a distributed system?',
'["Splitting data across multiple databases", "Storing copies of the same data on multiple machines for redundancy", "Removing duplicate records", "Compressing data for storage"]',
1,
'Data replication stores copies of the same data on multiple machines, providing redundancy, fault tolerance, and improved availability.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is the difference between IaaS, PaaS, and SaaS?',
'["They are all the same type of cloud service", "IaaS provides infrastructure, PaaS provides a development platform, SaaS provides ready-to-use software", "IaaS is the most expensive, SaaS is the cheapest", "PaaS is for storage only"]',
1,
'IaaS provides infrastructure (servers, VMs). PaaS provides a platform for developing and managing applications. SaaS provides ready-to-use software over the internet.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is a Jupyter Notebook?',
'["A type of database", "A web application for creating documents with live code, visualizations, and narrative text", "A cloud computing platform", "A machine learning algorithm"]',
1,
'A Jupyter Notebook is an open-source web application for creating documents containing live code, equations, visualizations, and narrative text.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'Name two popular programming languages used in data science.',
'["Java and C++", "Python and R", "HTML and CSS", "Swift and Kotlin"]',
1,
'Python and R are the two most popular programming languages in data science, offering extensive libraries for data analysis and machine learning.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is a foreign key in a relational database?',
'["A column that uniquely identifies each row", "A column that links to the primary key of another table", "A column that allows NULL values", "The first column in a table"]',
1,
'A foreign key is a column that provides a link between data in two tables by referring to the primary key of another table.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is reinforcement learning?',
'["Learning from labeled data", "Learning from unlabeled data to find patterns", "Learning by interacting with an environment and receiving rewards or penalties", "Learning by memorizing the training data"]',
2,
'Reinforcement learning is where an agent learns to make decisions by interacting with an environment, receiving rewards or penalties. Example: Training a model to play chess.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is underfitting?',
'["When a model learns the training data too well", "When a model is too simple to capture the underlying structure of the data", "When a model has too many features", "When the training data is too large"]',
1,
'Underfitting occurs when a model is too simple and fails to capture the underlying structure, performing poorly on both training and new data.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is a flat file?',
'["A file stored in a cloud database", "A simple database file with records and no structured relationships, like a CSV", "A compressed archive file", "A file with complex table relationships"]',
1,
'A flat file is a simple database file containing records without structured relationships, typically one table of data. Example: A CSV file.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is metadata and why is it important?',
'["Raw data that needs processing", "Data about data that provides context like source, format, and meaning", "The largest table in a database", "Encrypted data for security"]',
1,
'Metadata is data about data. It provides information such as source, format, creation date, and meaning. It is important for data discovery and governance.'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is Variability in the context of Big Data?',
'["The size of the data", "The inconsistency in the data''s meaning or flow over time", "The speed of data processing", "The number of data sources"]',
1,
'Variability refers to the inconsistency in the data''s meaning or flow. Data meaning can constantly change, or velocity can be inconsistent (e.g., traffic spikes).'),

('203ee6ac-e5c8-4644-bb3c-855884ba8de4',
'What is data transformation?',
'["Deleting unwanted data", "Converting data from one format or structure to another", "Combining data from multiple sources", "Storing data in a warehouse"]',
1,
'Data transformation is converting data from one format or structure to another. Example: Normalization (scaling numerical data to fit within a specific range like 0 to 1).');
