
-- Insert CS courses from CCMAS 2025-2026 handbook (skip existing COS 101, MTH 101)
-- 100 Level First Semester
INSERT INTO public.courses (code, title, level, semester, units, department, status, description, overview) VALUES
('PHY 101', 'General Physics I', '100', 'First', 3, 'Computer Science', 'C', 'Fundamental concepts of physics including mechanics, heat, and properties of matter.', 'Space and Time, Units and Dimension, Kinematics, Dynamics, Statics, Work and Energy, Conservation Laws, Simple Harmonic Motion, Waves and Wave Motion, Sound, Fluid Mechanics, Temperature and Heat, Kinetic Theory of Gases, First and Second Laws of Thermodynamics.'),
('PHY 107', 'General Practical Physics I', '100', 'First', 1, 'Computer Science', 'C', 'Practical laboratory sessions complementing General Physics I.', 'This course emphasizes quantitative measurements, the treatment of measurement errors, and graphical analysis. Students perform a range of experiments in mechanics and properties of matter, including experiments in viscosity, elasticity, surface tension, and mechanics.'),
('GST 111', 'Communication in English', '100', 'First', 2, 'Computer Science', 'C', 'English language communication skills for academic and professional contexts.', 'Effective communication and writing skills. Listening and note-taking skills. Comprehension and summary. Vocabulary development. Oral presentation and public speaking. Writing essays, letters, reports and memos. Use of the library and internet for research.'),
('GST 112', 'Nigerian Peoples and Culture', '100', 'First', 2, 'Computer Science', 'C', 'Study of Nigerian diverse peoples, cultures, history and national development.', 'Nigerian history, culture, arts, and philosophy. Study of the Nigerian environment, its peoples, their culture, and how these have contributed to national development. Multi-ethnic nature of Nigeria, cultural diversity, and national integration.'),
-- 100 Level Second Semester
('COS 102', 'Problem Solving', '100', 'Second', 3, 'Computer Science', 'C', 'Systematic problem-solving techniques using computational thinking and algorithms.', 'Problem-solving strategies and techniques. Algorithmic thinking and pseudocode. Flowcharts and problem decomposition. Abstraction and pattern recognition. Introduction to programming logic. Applied problem solving across various domains.'),
('MTH 102', 'General Mathematics II', '100', 'Second', 3, 'Computer Science', 'C', 'Continuation of elementary mathematics covering calculus and analytical geometry.', 'Functions of a real variable. Limits and continuity. Differentiation and its applications. Integration: techniques and applications. Taylor and Maclaurin series. Analytical geometry: conic sections, polar coordinates.'),
('PHY 102', 'General Physics II', '100', 'Second', 3, 'Computer Science', 'C', 'Fundamental concepts of electricity, magnetism, and modern physics.', 'Electrostatics: charges, electric fields, Gauss law, capacitance. Current electricity: Ohm law, circuits, Kirchhoff laws. Magnetostatics: magnetic fields, Ampere law, electromagnetic induction. Electromagnetic waves. Optics: reflection, refraction, interference, diffraction. Introduction to modern physics.'),
('PHY 108', 'General Practical Physics II', '100', 'Second', 1, 'Computer Science', 'C', 'Practical laboratory sessions complementing General Physics II.', 'Laboratory experiments in electricity, magnetism, and optics. Electrical measurements using meters and oscilloscopes. Experiments on electromagnetic induction, lenses, mirrors, and interference of light.'),
-- 200 Level First Semester
('COS 201', 'Computer Programming I', '200', 'First', 3, 'Computer Science', 'C', 'Introduction to structured programming using a high-level language.', 'Introduction to programming paradigms. Variables, data types, operators. Control structures: selection, iteration. Functions and modular programming. Arrays and strings. File handling. Introduction to debugging and testing. Problem solving with C/Python programming.'),
('COS 203', 'Discrete Structures', '200', 'First', 3, 'Computer Science', 'C', 'Mathematical structures fundamental to computer science.', 'Logic and proofs. Sets, relations, and functions. Combinatorics and counting. Graph theory. Trees and their applications. Boolean algebra. Recurrence relations. Algorithms and their complexity. Mathematical induction.'),
('COS 205', 'Operating Systems I', '200', 'First', 3, 'Computer Science', 'C', 'Fundamental concepts and principles of operating systems.', 'Introduction to operating systems. Process management: processes, threads, scheduling. Memory management: paging, segmentation, virtual memory. File systems and I/O management. Deadlock handling. Introduction to concurrency and synchronization.'),
('COS 207', 'Data Structures and Algorithms', '200', 'First', 3, 'Computer Science', 'C', 'Fundamental data structures and algorithm design techniques.', 'Abstract data types. Arrays, linked lists, stacks, queues. Trees: binary trees, BST, AVL trees, heaps. Hashing and hash tables. Graphs and graph algorithms. Sorting algorithms. Searching algorithms. Algorithm analysis: time and space complexity. Recursion.'),
('ENT 211', 'Entrepreneurship and Innovation', '200', 'First', 2, 'Computer Science', 'C', 'Fundamentals of entrepreneurship, innovation, and new venture creation.', 'Introduction to entrepreneurship. Opportunity identification and evaluation. Business model canvas. Innovation and creativity. Feasibility analysis. Business plan development. Marketing fundamentals for entrepreneurs. Financial management basics.'),
('GST 212', 'Philosophy, Logic and Human Existence', '200', 'First', 2, 'Computer Science', 'C', 'Introduction to philosophy, logic, and critical thinking.', 'Introduction to philosophy. Branches of philosophy. Logic and critical thinking. Deductive and inductive reasoning. Fallacies. Philosophy of science. Ethics and moral philosophy. Human existence and the meaning of life.'),
-- 200 Level Second Semester
('COS 202', 'Computer Programming II', '200', 'Second', 3, 'Computer Science', 'C', 'Advanced programming concepts including object-oriented programming.', 'Object-oriented programming concepts. Classes, objects, inheritance, polymorphism. Encapsulation and abstraction. Exception handling. Generic programming. Collections framework. GUI programming basics. Design patterns introduction. Advanced problem solving using Java/C++.'),
('COS 204', 'Computer Architecture and Organization', '200', 'Second', 3, 'Computer Science', 'C', 'Design and organization of computer systems and their components.', 'Number systems and data representation. Boolean algebra and logic gates. Combinational and sequential circuits. CPU architecture: ALU, registers, control unit. Instruction set architecture. Memory hierarchy: cache, main memory. I/O systems and buses. Introduction to parallel architectures.'),
('COS 206', 'Introduction to Database Systems', '200', 'Second', 3, 'Computer Science', 'C', 'Fundamentals of database design, management and querying.', 'Database concepts and architecture. Entity-Relationship modeling. Relational data model. SQL: DDL, DML, queries. Normalization theory. Transaction management. Concurrency control. Database security. Introduction to NoSQL databases.'),
('COS 208', 'Web Technologies', '200', 'Second', 3, 'Computer Science', 'C', 'Design and development of web-based applications and technologies.', 'Internet and WWW fundamentals. HTML5 and CSS3. JavaScript programming. Responsive web design. Client-server architecture. Server-side programming basics. Web frameworks introduction. Web APIs and RESTful services. Web security fundamentals.'),
('STA 201', 'Statistics for Physical Sciences and Engineering', '200', 'Second', 3, 'Computer Science', 'C', 'Statistical methods and probability theory for science and engineering.', 'Descriptive statistics. Probability theory. Random variables and distributions. Sampling distributions. Estimation and hypothesis testing. Correlation and regression analysis. Analysis of variance. Non-parametric methods.'),
-- 300 Level First Semester
('COS 301', 'Software Engineering I', '300', 'First', 3, 'Computer Science', 'C', 'Principles and practices of software engineering and development methodologies.', 'Software development life cycle. Requirements engineering. Software design: architectural, detailed. Agile methodologies: Scrum, Kanban. Version control systems. Software testing strategies. Quality assurance. Project management. UML modeling.'),
('COS 303', 'Theory of Computing', '300', 'First', 3, 'Computer Science', 'C', 'Formal languages, automata theory, and computational complexity.', 'Finite automata and regular expressions. Context-free grammars and pushdown automata. Turing machines and computability. Undecidability. Computational complexity: P, NP, NP-completeness. Formal language hierarchy.'),
('COS 305', 'Computer Networks', '300', 'First', 3, 'Computer Science', 'C', 'Principles and practice of computer networking and data communications.', 'Network models: OSI and TCP/IP. Physical layer: signals, media, encoding. Data link layer: framing, error detection. Network layer: routing algorithms, IP addressing. Transport layer: TCP, UDP. Application layer protocols. Network security basics. Wireless networks.'),
('COS 307', 'Artificial Intelligence', '300', 'First', 3, 'Computer Science', 'C', 'Introduction to artificial intelligence concepts and techniques.', 'Introduction to AI and its history. Problem solving and search strategies. Knowledge representation and reasoning. Expert systems. Machine learning fundamentals. Neural networks basics. Natural language processing introduction. Computer vision basics. AI ethics.'),
('COS 309', 'Systems Analysis and Design', '300', 'First', 3, 'Computer Science', 'C', 'Systematic approaches to analyzing and designing information systems.', 'Systems analysis concepts and methodology. Requirements gathering techniques. Data flow diagrams. Process modeling. Data modeling. System design principles. Interface design. Implementation planning. Change management.'),
('GST 312', 'Peace and Conflict Resolution', '300', 'First', 2, 'Computer Science', 'C', 'Study of peace concepts, conflict dynamics and resolution mechanisms.', 'Concepts of peace and conflict. Types and causes of conflict. Conflict analysis frameworks. Negotiation and mediation. Conflict resolution mechanisms. Peacebuilding strategies. Human rights. International humanitarian law.'),
('ENT 312', 'Venture Creation', '300', 'First', 2, 'Computer Science', 'C', 'Practical venture creation from ideation to launch.', 'Business opportunity identification. Market research and analysis. Business plan writing. Legal aspects of venture creation. Funding and financing options. Marketing strategy development. Operations management. Business growth strategies.'),
-- 300 Level Second Semester
('COS 302', 'Software Engineering II', '300', 'Second', 3, 'Computer Science', 'C', 'Advanced software engineering topics including design patterns and architecture.', 'Advanced software design patterns. Software architecture styles. Software metrics and estimation. Configuration management. Software maintenance and evolution. DevOps and CI/CD. Microservices architecture. Software reuse and component-based development.'),
('COS 304', 'Compiler Construction', '300', 'Second', 3, 'Computer Science', 'C', 'Principles and techniques of compiler design and implementation.', 'Lexical analysis and scanning. Syntax analysis: top-down and bottom-up parsing. Semantic analysis. Intermediate code generation. Code optimization techniques. Code generation. Symbol table management. Error handling and recovery.'),
('COS 306', 'Human Computer Interaction', '300', 'Second', 3, 'Computer Science', 'C', 'Principles of designing effective user interfaces and user experiences.', 'Foundations of HCI. Human cognitive abilities and limitations. Interaction design principles. Usability engineering. User-centered design process. Prototyping techniques. Evaluation methods: heuristic, user testing. Accessibility. Mobile and web interface design.'),
('COS 308', 'Numerical Computation', '300', 'Second', 3, 'Computer Science', 'C', 'Numerical methods and computational techniques for solving mathematical problems.', 'Errors in numerical computation. Solution of nonlinear equations. Systems of linear equations. Interpolation and approximation. Numerical differentiation and integration. Numerical solution of ordinary differential equations. Eigenvalue problems.'),
('COS 310', 'Introduction to Machine Learning', '300', 'Second', 3, 'Computer Science', 'C', 'Foundational concepts and algorithms in machine learning.', 'Introduction to machine learning paradigms. Supervised learning: regression, classification. Decision trees and random forests. Support vector machines. Neural networks and deep learning basics. Unsupervised learning: clustering, dimensionality reduction. Model evaluation and validation. Feature engineering.'),
('COS 399', 'Students Industrial Work Experience (SIWES)', '300', 'Second', 6, 'Computer Science', 'C', 'Supervised industrial training providing real-world work experience.', 'Minimum 24 weeks of supervised industrial training in IT-related industries. Students gain practical experience in software development, networking, database administration, or related fields. Assessment through log book, written report, and seminar presentation.'),
-- 400 Level First Semester
('COS 401', 'Formal Methods and Software Verification', '400', 'First', 3, 'Computer Science', 'C', 'Formal techniques for specifying, developing, and verifying software systems.', 'Introduction to formal methods. Propositional and predicate logic. Formal specification languages: Z, VDM. Program correctness and verification. Model checking. Theorem proving. Formal methods in practice. Safety-critical systems.'),
('COS 403', 'Computer Security', '400', 'First', 3, 'Computer Science', 'C', 'Principles and practices of computer and information security.', 'Security fundamentals: CIA triad. Cryptography: symmetric, asymmetric, hashing. Authentication and access control. Network security: firewalls, IDS/IPS, VPN. Web security: XSS, CSRF, SQL injection. Malware analysis. Security policies and risk management. Digital forensics introduction.'),
('COS 405', 'Cloud Computing', '400', 'First', 3, 'Computer Science', 'E', 'Cloud computing models, architectures, and deployment strategies.', 'Cloud computing concepts and characteristics. Service models: IaaS, PaaS, SaaS. Deployment models: public, private, hybrid. Virtualization and containerization. Cloud storage and databases. Cloud security. Serverless computing. DevOps in the cloud. Major cloud providers: AWS, Azure, GCP.'),
('COS 407', 'Distributed Systems', '400', 'First', 3, 'Computer Science', 'E', 'Design and implementation of distributed computing systems.', 'Distributed systems concepts and architecture. Communication protocols: RPC, message passing. Distributed file systems. Consistency and replication. Fault tolerance. Distributed transactions. Consensus algorithms. Peer-to-peer systems. MapReduce and distributed computing frameworks.'),
('COS 409', 'Research Methodology and Technical Report Writing', '400', 'First', 3, 'Computer Science', 'C', 'Research methods, academic writing, and technical communication skills.', 'Research methodology overview. Literature review techniques. Research design: qualitative, quantitative, mixed methods. Data collection and analysis methods. Technical writing standards. Citation and referencing. Scientific paper writing. Presentation skills. Research ethics.'),
('COS 499', 'Final Year Project I', '400', 'First', 3, 'Computer Science', 'C', 'First phase of the capstone project: proposal, design, and initial implementation.', 'Project topic selection and proposal writing. Literature review and background research. System requirements analysis. System design and architecture. Initial implementation and prototyping. Project documentation. Presentation of project proposal and preliminary results.'),
-- 400 Level Second Semester
('COS 402', 'Advanced Database Systems', '400', 'Second', 3, 'Computer Science', 'C', 'Advanced topics in database systems and data management.', 'Distributed databases. Object-relational databases. Data warehousing and OLAP. Big data technologies. NoSQL databases: document, key-value, graph. Database performance tuning. Data mining and knowledge discovery. Cloud databases. Database security advanced topics.'),
('COS 404', 'Internet of Things', '400', 'Second', 3, 'Computer Science', 'E', 'Design and development of IoT systems and applications.', 'IoT architecture and protocols. Sensors and actuators. Embedded systems programming. IoT communication: MQTT, CoAP. Edge computing. IoT platforms and middleware. IoT data analytics. IoT security challenges. Smart applications: healthcare, agriculture, cities.'),
('COS 406', 'Natural Language Processing', '400', 'Second', 3, 'Computer Science', 'E', 'Computational techniques for processing and understanding human language.', 'Introduction to NLP. Text preprocessing and tokenization. Language models. Part-of-speech tagging. Named entity recognition. Sentiment analysis. Machine translation. Text classification and summarization. Transformer architecture. Large language models.'),
('COS 408', 'Data Mining and Knowledge Discovery', '400', 'Second', 3, 'Computer Science', 'E', 'Techniques for extracting patterns and knowledge from large datasets.', 'Data mining process and methodologies. Data preprocessing and transformation. Association rule mining. Classification techniques. Clustering algorithms. Anomaly detection. Sequential pattern mining. Text mining. Web mining. Data mining tools and applications.'),
('COS 410', 'Seminar', '400', 'Second', 2, 'Computer Science', 'C', 'Research seminar with presentations on current topics in computer science.', 'Students research and present seminars on current and emerging topics in computer science. Topics include AI, cybersecurity, blockchain, quantum computing, and other frontier areas. Peer review and academic discussion skills are developed.'),
('COS 498', 'Final Year Project II', '400', 'Second', 3, 'Computer Science', 'C', 'Completion and defense of the capstone project.', 'Continuation and completion of the final year project. Full system implementation and testing. Project documentation and technical report writing. Project defense and presentation. Demonstration of the completed system.')
ON CONFLICT (code) DO NOTHING;
