-- Update content_text for ICT 201 materials
UPDATE materials SET content_text = 'Week 1: ICT Principles. ICT is an umbrella term covering all advanced technologies in manipulating and communicating information. ICT three main components: Computers (Hardware, Programs, Information), Communications networks, Know-how (People, Applications). A computer is an electronic system that can be instructed to accept, process, store, and present data and information. Hardware is the computer and its associated equipment. Software is a set of instructions that controls a computer. Data is raw facts, figures, and details. Information is an organized, meaningful, and useful interpretation of data. Knowledge is an awareness and understanding of information. Computers come in four sizes: Microcomputers, Midrange computers, Mainframes, Supercomputers. Communications Network is a set of locations or nodes linked together as a system. IT has nine major functions: Capture, Verifying, Processing/Manipulation, Storage, Retrieval, Data Update, Reproducing, Transmission/Communication, Generation. Benefits of ICT are speed, consistency, accuracy and reliability.' WHERE id = '277f8f03-239c-45c3-9d8b-4e4450d87572';

UPDATE materials SET content_text = 'Week 2: Essentials of Computing. Computer: An electronic system that accepts data as input, processes it and gives output. Computer System made up of Hardware and Software. Five components: Hardware, People, Programs, Procedures, Information. Hardware classified into Input devices, Output devices, Storage, System unit. Software: System software and Application software. System software: operating systems, utilities, device drivers, language translators. Operating Systems three categories: Embedded, Network (NOS), Stand-alone. Application software: Basic and Specialized. IT Users: Hands-on users, Indirect end users, User managers, Senior managers. IT Professionals: Programmers, Systems Analysts, System Designers, Web Designers, Project Managers, Network Specialists, Trainers, Computer Operators. Procedures: Operations, Backup and Recovery, Security, Development.' WHERE id = 'b0a6a020-c34d-4f11-af62-0de913258dd2';

UPDATE materials SET content_text = 'Week 3: System Unit and CPU. The System Unit houses processor, ports, power supply, motherboard, add-in boards and memory chips. CPU executes program instructions. Components: Integrated Circuits, Transistor, Control Unit, ALU. Machine Cycle: fetch, decode, execute, store. I-cycle (fetch and decode), E-cycle (execute and store). Register types: Storage, Address, Accumulators. Processor Speed: Millisecond, Microsecond, Nanosecond, Picoseconds. MIPS and Megaflops. Determining speed: System Clock, Bus Width, Word Size, Available Memory. MHz and GHz. Cache Memory. USB connects up to 128 devices. Plug and Play. Add-in Boards: Accelerator, Controller, Coprocessor, Display Adaptor, Fax Modem, Memory expansion, Network interface.' WHERE id = '18a16cf7-7fd6-42eb-a8c5-196005511baf';

UPDATE materials SET content_text = 'Week 4: Input/Output/Storage/Memory. Input Devices enable data transmission into computer. Types: Keyboard, Terminal, Scanners, OCR, Digitizers, Pointing Devices, Digital Camera, Bar Code, Mouse. Output Device makes processing results available outside computer. Types: Monitors, Data Projector, Printers, Audio Response Unit, Television, Plotter, Film Recorder. Storage holds data permanently. Memory is volatile, used to load programs. Memory sizes: Byte, Kilobyte, Megabyte, Gigabyte, Terabyte.' WHERE id = 'a93f9726-6f6d-4b3e-a03b-a0cf43ba90f4';

UPDATE materials SET content_text = 'Week 5: Computer Networks. Computer Networking: techniques and connections to interlink computers to share resources. Two connection types: Physical and Logical/Virtual. TCP/IP used by Internet. Three components: Network Software (protocols, packets), Application Software (client-server, peer-to-peer), Network Hardware (cables, NIC, modem). Networking Devices: NIC, Hubs, Switches, Routers, Modems, Bridges. Security: Authentication, Authorization, Audits, Firewalls. OSI Model seven layers: Physical, Data Link, Network, Transport, Session, Presentation, Application. Network types: LAN, WAN, MAN, CAN, PAN. Topologies: Point-to-Point, Bus, Star, Ring, Tree. Network Channels: Twisted Pair, Coaxial Cable, Fiber-optic, Microwave, Satellite, Infrared, Radio Waves. Packet Switching divides messages into packets.' WHERE id = '84e3023c-757f-48c7-8bb3-ddb3c1f4d908';

UPDATE materials SET content_text = 'Week 6: Enterprise and Wireless Networks. Four wireless forms: Cellular Communication Service, WLAN, Bluetooth PAN, Wireless Data Networks. MTSO links cell tower to PSTN. TDMA divides frequency into time slots. CDMA encodes with unique identification code. GPRS (2.5G), 3G (384 Kbs to 2 Mbs), GPS. WLAN transmits via radio frequencies. WEP encrypts data. SSID for network access. Bluetooth: short-range radio links (10 meters). VPN uses encryption for secure access. NOS manages network. Enterprise Architectures: Centralized, Distributed, Hybrid. Virtual Company joins operationally not physically.' WHERE id = '10b9b5ea-32f2-4e66-b810-78364f11dbf1';

UPDATE materials SET content_text = 'Week 7: Essentials of the Internet. Internet launched 1969 as ARPANET. Connectivity: capability to share information. Client Computer accesses server information. Surfing: moving among interlinked networks. Capabilities: Communicate, Retrieve, Research, Shopping. Communication: E-mail, Mailing Lists, Newsgroups, IRC, Instant Messages, VoIP, Telnet. Retrieval: FTP, Web Directory, Search Engines, Portal, Webcasting, Streaming. Research: locating, evaluating, citing references. Plagiarism is illegal copying. Providers: ISPs, ASPs, Content Providers, Infrastructure Providers.' WHERE id = '21e6c16e-3ae2-46fb-b474-f633cf95f42e';

UPDATE materials SET content_text = 'Week 8: E-Commerce. Electronic commerce is buying and selling over the Internet. Buyers: purchase anytime. Sellers: no physical store needed. Three types: B2C (business-to-consumer, fastest growing), C2C (consumer-to-consumer, auctions), B2B (business-to-business, manufacturer-supplier). B2C applications: Online banking, Financial trading, Shopping. Benefits: Geographic Reach, Speed, Productivity, Information Sharing, New Features, Lower Costs, Competitive Advantage. Payment: check, credit card, electronic cash.' WHERE id = '2dfb9eed-49f3-4faf-96b2-04d0b583a407';

UPDATE materials SET content_text = 'Week 9: Launching IT Applications Projects. Two categories: Single-user/Personal System and Enterprise System. Enterprise involves server, database, network. Impact: Improved Productivity, Greater Effectiveness, Increased Creativity. Systems Development: examining business situation, designing solution. Project Management: planning, organizing, integrating, overseeing. Project Proposal submitted to Steering Committee.' WHERE id = '5b391893-68a5-4f4b-a21f-029e00b68c72';

UPDATE materials SET content_text = 'Week 10: Creating Enterprise Applications and Project Management. Enterprise systems developed by MIS department. Development Alternatives: Build, Purchase, Contract out. Open System runs on different hardware. Interoperability: perfect exchange of data. Project management matches goals, tasks, resources. Seven stages: Define goals, Define tasks, Determine resources, Identify risks, Develop schedule, Execute schedule, Finish and assess. ASPs allow access to application programs.' WHERE id = 'acacac65-944b-437b-89af-e34b4e7c2dc5';

-- Insert theory quiz questions for ICT 201 (verbatim from slides)
INSERT INTO theory_quiz_bank (course_id, question, reference_answer) VALUES
-- Week 1 questions
('ca315991-ea5c-40bc-b725-78114f252c36', 'What is Information and Communication Technology (ICT)?', 'Information and communication technologies (ICT) is an umbrella term that covers all advanced technologies in manipulating and communicating information. ICT is concerned with the storage, retrieval, manipulation, transmission or receipt of digital data.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'What are the three main components of ICT?', 'ICT three main components are: Computers (used to process data into information - Hardware, Programs, Information), Communications networks (transmission of information), and Know-how (the technology used for transmission - People, Applications).'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'Define a computer, hardware, software, and program.', 'A computer is an electronic system that can be instructed to accept, process, store, and present data and information. Hardware is the computer and its associated equipment. Software is the general term for a set of instructions that controls a computer or a communications network. A program is a set of instructions that directs a computer to perform certain tasks and produce certain results.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'What is the difference between data, information, and knowledge?', 'Data is raw facts, figures, and details. Information is an organized, meaningful, and useful interpretation of data. Knowledge is an awareness and understanding of a set of information and how that information can be put to the best use.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'List and explain the nine major functions of Information Technology.', '1. Capture - compiling detailed records of activities, 2. Verifying - checking or validating data, 3. Processing/Manipulation - converting, analyzing, computing, and synthesizing data, 4. Storage - placing data onto storage media, 5. Retrieval - searching out and gaining access to specific data, 6. Data Update - making changes to stored data, 7. Reproducing - duplicating data from one medium to another, 8. Transmission/Communication - distributing information over a communications network, 9. Generation - organizing information into a useful form.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'What are the four sizes of computers?', 'Computers come in four sizes: Microcomputers, Midrange computers, Mainframes, and Supercomputers.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'Define Communications Network and Data Communication.', 'Communications Network is a set of locations, or nodes, consisting of hardware, programs, and information linked together as a system that transmits and receives data and information. Data Communication is the transmission of data and information through a communications medium.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'What is Know-how in the context of Information Technology?', 'Know-how is the capability to do something well. Information technology know-how consists of: Familiarity with the tools of IT including the Internet, Possession of the skills needed to use these tools, and An understanding of when to use IT to solve a problem or create an opportunity.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'What are the benefits of Information and Communication Technology?', 'The benefits of ICT are Information processing speed, consistency, accuracy and reliability.'),

-- Week 2 questions
('ca315991-ea5c-40bc-b725-78114f252c36', 'What are the five components of a computer system?', 'The five components of a computer system are: Hardware, People (People Ware), Programs (Software), Procedures, and Information.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'What are the four categories of hardware in a computer system?', 'The four categories are: Input devices (Keyboard, Mouse, Scanner, Camera etc), Output devices (Printers, plotters etc), Storage (Hard disk, floppy disk, CD, flash drives etc), and System unit (SU).'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'Explain the difference between system software and application software.', 'System software focuses on handling technical details. It works with end users, application programs, and computer hardware to handle many details relating to computer operations. Application software focuses on completing specific tasks or applications. There are two categories of application software: Basic applications (general-purpose/productivity applications) and Specialized applications (special-purpose applications).'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'What are the four kinds of system programs?', 'Four kinds of system programs are: Operating Systems (coordinates resources, provides interface, runs programs), Utilities/service programs (performs specific tasks related to managing resources), Device Drivers (programs developed by manufacturers to make devices work on different platforms), and Language Translators (converts programming instructions into computer-understandable language).'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'List the three basic categories of operating systems.', 'There are three basic categories: Embedded (for handheld computers and small devices), Network or NOS (control and coordinate computers on a network), and Stand-alone/desktop (for desktop and notebook computers, called client operating systems in networked environment).'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'What are the common features of most application programs?', 'Common features include: User interface (most have GUI that displays icons), Windows (rectangular areas containing documents, programs, messages), Menus (commands listed on menu bar with pull-down/drop down menus), Dialog box (provides additional information or requests user input), and Toolbars (contains buttons and menus).'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'Who are the users of IT resources and what are the categories of IT professionals?', 'IT Users: Hands-on users (use computers directly), Indirect end users (benefit from IT as recipients), User managers (supervisory responsibility), Senior managers (evaluate organization dependence on IT). IT Professionals: Programmers, Systems Analysts, System Designers, Web Designers, Project Managers, Network Specialists, Trainers, Computer Operators.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'Define the types of IT procedures.', 'A Procedure is a step-by-step process for accomplishing specific results. Types: Operations Procedure (describes how a system is used), Backup Procedure (how and when to make extra copies), Recovery Procedure (action taken when information must be restored), Security Procedure (safeguards data centers and networks), Development Procedure (explains how to describe user needs and develop applications).'),

-- Week 3 questions
('ca315991-ea5c-40bc-b725-78114f252c36', 'What is the System Unit and what does it house?', 'The System Unit is the hardware unit that houses a computer''s processor, ports, power supply, casing, motherboard and add-in boards and memory chips.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'What is the Central Processing Unit (CPU) and what are its components?', 'The CPU or Processor is the computer hardware that executes program instructions and performs the computer''s processing actions. Components: Integrated Circuits/Chip/Microchip (collection of thousands or millions of transistors on a small silicon chip), Transistor (electrical switch in open or closed state), Control Unit (oversees and controls all computer activities), and Arithmetic/Logic Unit (ALU - performs arithmetic and logical operations).'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'Explain the Machine Cycle and its four steps.', 'The Machine Cycle consists of four processing steps performed by the control unit: fetch, decode, execute, and store. The Instruction Cycle (I-cycle) is the first two steps (fetch and decode) where instructions are obtained and translated. The Execution Cycle (E-cycle) is the last two steps (execute and store) which produce processing results.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'What are the units of processor speed?', 'Millisecond: One thousandth of a second. Microsecond: One millionth of a second. Nanosecond: One billionth of a second. Picoseconds: One trillionth of a second. MIPS: Millions of Instructions per Second. Megaflops: Millions of floating point operations per second.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'What four elements are considered when determining Processor Speed?', 'Four elements: System Clock (circuit generating electronic impulses at fixed rate, measured in MHz and GHz), Bus Width (I/O bus moves data in/out of processor, Data Bus moves data between CPU and memory), Word Size (number of bits a computer can process at one time), and Available Memory.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'Define Port, USB, and Plug and Play.', 'Port: A connector through which input/output devices can be plugged into the computer. Universal Serial Bus (USB): A general purpose port that can connect up to 128 devices, and also hot swappable, meaning devices can be plugged in or unplugged without shutting down. Plug and Play: The ability to install devices into a computer when the computer itself makes any necessary internal adjustments.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'What is a Register and what are its types?', 'A Register is a temporary storage area in the processor that can move data and instructions more quickly than main memory can, and momentarily holds the data or instructions used in processing as well as the results generated. There are three types: Storage Registers, Address Registers, and Accumulators.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'Explain Pipelining, Parallel Processing, and Sequential Processing.', 'Pipelining: A computer starts processing a new instruction as soon as the previous instruction reaches its next step in the processing cycle. Parallel Processing: Processing in which a computer handles different parts of a problem by executing instructions simultaneously. Sequential Processing: Processing in which the execution of one instruction is followed by the execution of another.'),

-- Week 4 questions
('ca315991-ea5c-40bc-b725-78114f252c36', 'What are Input Devices and list the types?', 'Input Devices are devices which enable data, information and instructions to be transmitted into the Computer system. They act as a gateway for receiving input usually in user understandable form from the outside world and convert it to machine understandable form. Types include: Keyboard, Terminal, Scanners, Optical Character Recognition (OCR), Digitizers, Pointing Devices, Digitizing Table, Digital Camera, Digital Video Camcorders, Voice and Sound Input Devices, Bar Code, Wand, Multimedia, Mouse.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'What is an Output Device and list the types?', 'Output Device is a device that makes the results of processing available outside of the computer to be used in business decision making. It brings out the information after the data has been processed. Types include: Visual Displays (Monitors), Data Projector, Printers, Audio Response Unit, Television, Plotter, Film Recorder.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'What is the difference between storage and memory?', 'Storage and memory look similar but perform different tasks. Memory is used to load program files and is volatile, while storage is used to hold data permanently and to be retrieved for future use. Memory serves the purpose of temporary storage (holding data and instruction) and also used to boot the computer system. Storage comes in different types, sizes, and technologies.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'List and define the memory size units.', 'Byte: basic unit of storage. Kilobyte (KB/K): approximately 1,000 bytes. Megabyte (MB/Meg): approximately 1,000,000 bytes. Gigabyte (GB/Gig): approximately 1,000,000,000 bytes. Terabyte (TB): approximately 1,000,000,000,000 bytes. Address: the location of data in memory.'),

-- Week 5 questions
('ca315991-ea5c-40bc-b725-78114f252c36', 'What is Computer Networking and what are the two types of network connections?', 'Computer Networking refers to the techniques, physical connections, and programs used to interlink two or more computers together to enable them share resources such as hard discs, modems, printers. Two types: Physical connections (let computers directly transmit and receive signals, defined by medium, topology, and sharing method) and Logical or virtual connections (allow computer applications to exchange information using network protocols).'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'What are the three essential components of a network?', 'Network Software (programs that establish protocols or rules for computers to talk to one another using packets), Application Software (programs that interface with network users - types are client-server and peer-to-peer), and Network Hardware (computers, nodes, cables, connectors and network adapters like NIC, modem, wireless cards).'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'List and explain the seven layers of the OSI Model.', '1. Physical Layer: level of electrical connections and signal transmission. 2. Data Link Layer: data transmitted in small units (frames) using protocols. 3. Network Layer: provides control among adjacent sending and receiving points. 4. Transport Layer: provides end-to-end service between host computers. 5. Session Layer: handles establishment of connections and dialogue management. 6. Presentation Layer: handles standard forms for presenting data. 7. Application Layer: level which user has control over in determining what data is transmitted.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'What are the different types of network topologies?', 'Network topologies: Point-to-Point (simplest, two connected computers), Bus (single link connected to many computers, all receive all signals), Star (connects many computers to a common hub), Ring (multiple links forming a circle, information moves in sequence), Tree (combines bus and star characteristics, groups of star-configured workstations connected to bus backbone cable).'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'What are the types of computer networks by size?', 'Local Area Networks (LAN), Wide Area Networks (WAN), Metropolitan Area Networks (MAN), Campus Area Networks (CAN), and Personal Area Networks (PAN).'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'What are the three basic forms of network security?', 'User authentication and authorization (Authentication designates who can access the network, Authorization governs what they can see), Audits (track user activity to help spot unauthorized activity), and Firewalls (protect internal network from invasion through the Internet or other external sources, can restrict access to certain users and control which applications they use).'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'Describe the physical and wireless network channels.', 'Physical Channels: Twisted Pair (strands of copper wire twisted in pairs), Coaxial Cable (central wire conductors surrounded by insulator, includes Baseband and Broadband), Fiber-optic Cable (uses light and glass fibers). Wireless Channels: Microwave (high-frequency radio signals through air), Satellite (communications beamed to orbiting satellite), LEO (low-earth-orbit satellite), VSAT (Very Small Aperture Terminal), Infrared (coded infrared light beams), Radio Waves (frequencies rented from public radio networks).'),

-- Week 6 questions
('ca315991-ea5c-40bc-b725-78114f252c36', 'What are the four forms of wireless communications?', 'The four wireless forms are: Cellular Communication Service (transmits radio messages between mobile device and cell site), Wireless LAN/WLAN (transmit data using radio frequencies instead of cables), Bluetooth Personal Area Network (short-range radio links of 30 feet or 10 meters between devices), and Wireless Data Networks (use cellular services to support mobile users).'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'Explain TDMA, CDMA, GPRS, and 3G.', 'TDMA (Time Division Multiple Access): divides a radio frequency into time slots and allocates slots to individual conversations. CDMA (Code Division Multiple Access): encodes each conversation with a unique identification code. GPRS (Generalized Packet Radio Service or 2.5G): higher speed transmission using packet switching. 3G (Third-generation Service): uses packet switching at higher bandwidths from 384 Kbs to 2 Mbs.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'What is a VPN and how does it work?', 'Virtual Private Network (VPN): A network constructed of public channels to connect client computers to server, incorporating encryption and other security mechanisms to ensure that only authorized users can gain access and that the data cannot be intercepted.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'Explain the three types of enterprise architectures.', 'Centralized Architecture: a computer at a central site hosts all of the network''s hardware and software, performs all processing, and manages the network. Distributed Architecture: computers reside at different locations and are interconnected by a communications network, includes distributed processing and distributed databases. Hybrid Network: combines centralized and distributed architectures to take advantage of strengths of both.'),

-- Week 7 questions
('ca315991-ea5c-40bc-b725-78114f252c36', 'What is the Internet and how did it originate?', 'The Internet is a huge computer network available to nearly everyone with a microcomputer and a means to connect to it. It was launched in 1969 when the United States funded a project that developed a national computer network called Advanced Research Agency Network (ARPANET). The Internet is a large network that connects smaller networks all over the globe together.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'Define Client Computer, Server Computer, and Client-server Computing.', 'Client Computer: The computer that accesses the information stored on a server computer. Server Computer: The computer that contains data and information that can be accessed by a client computer. Client-server Computing: A type of computing in which all data and information retrieval requests and responses pass over a network, with much of the processing performed on the server and results transmitted to the client.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'What are the communication and retrieval capabilities of the Internet?', 'Communication Capabilities: E-mail, Mailing Lists, Newsgroups, Chat Session or Internet Relay Chat (IRC), Instant Messages, Internet Telephony or Voice over IP, Telnet. Retrieval Capabilities: FTP (File Transfer Protocol), Web Directory, Search Engines, Portal, Webcasting, Streaming.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'What are the types of Internet providers?', 'Service Providers or Internet Service Providers (ISPs), Application Service Providers (ASPs), Content Providers, Infrastructure Providers, and Internet Support Agencies.'),

-- Week 8 questions
('ca315991-ea5c-40bc-b725-78114f252c36', 'What is Electronic Commerce and what are its three types?', 'Electronic commerce (e-commerce) is the buying and selling of goods over the Internet. Three types: Business-to-consumer (B2C) - fastest growing, sale to general public/end-users; Consumer-to-consumer (C2C) - individuals selling to individuals via electronic ads or auctions; Business-to-business (B2B) - sale from one business to another, typically manufacturer-supplier relationship.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'What are the benefits of E-Commerce?', 'Geographic Reach (distance not a barrier), Speed (near instant exchange), Productivity (more work in less time), Information Sharing (text, graphics, audio, video, animation transmitted), New Features (personalized, automatic notification), Lower Costs (reduced business costs), Competitive Advantage (effective e-commerce strategy provides advantages over competitors).'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'Describe the roles of buyers and sellers in e-commerce.', 'Buyers: goods and services can be purchased at any time of the day or night, don''t have to travel physically to seller''s location. Sellers: cost of renting a shop is eliminated, no in-store inventory needed, products shipped directly from warehouse.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'What are the three basic payment options in e-commerce?', 'The three basic payment options are: check, credit card, and electronic cash. The single greatest challenge for e-commerce is the development of fast, secure, and reliable payment method for purchased goods.'),

-- Week 9 questions
('ca315991-ea5c-40bc-b725-78114f252c36', 'What are the two categories of IT applications?', 'Single-user System/Personal System: An IT system used by only one person, stands alone and is not interconnected with other companies or shared. Enterprise System: Usually involves server or mainframe, database, and network, and is generally a shared system.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'What are the impacts of IT applications?', 'Improved Productivity: the relationship between the results of an activity (output) and the resources used (inputs). Greater Effectiveness: the extent to which desirable results are achieved. Increased Creativity and Innovation.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'Define Systems Development and Project Management.', 'Systems Development: The process of examining a business situation, designing a system solution to improve that situation, and acquiring the human, financial, and information technology resources needed to develop and implement the solution. Project Management: The process of planning, organizing, integrating, and overseeing the development of an IT application to ensure the project''s objectives are achieved and the system is implemented according to expectations.'),

-- Week 10 questions
('ca315991-ea5c-40bc-b725-78114f252c36', 'What are the three approaches to developing an enterprise application?', 'The information technology group can: Build the application itself, Purchase a prewritten application, or Contract out the application development.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'Define Open System and Interoperability.', 'Open System: A software system that runs on different computer and communications hardware. Interoperability: The perfect exchange of data and information in all forms (data, text, sound, and image, including animation) between the individual components of an application (hardware, software, and network).'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'What are the seven stages of a project?', 'Stage 1: Defining the goals of the project. Stage 2: Define project tasks/activities. Stage 3: Determine and verify resource requirements. Stage 4: Identify risks and develop mitigation (backup) plans. Stage 5: Develop a schedule. Stage 6: Execute the schedule. Stage 7: Finish the project and assessing performance.'),
('ca315991-ea5c-40bc-b725-78114f252c36', 'What is a Project Proposal and Steering Committee?', 'Project Proposal: A proposal for a systems project prepared by users or systems analysts and submitted to a steering committee for approval. Steering Committee: A group of people from various functional areas of a business that determines whether a systems development project proposal is desirable and should be pursued.');
