
-- Step 1: Delete all wrong/fake Computer Science courses (those not in the CCMAS 2025-2026 handbook)
-- COS 101 has data so we keep it. We delete all fabricated courses.
DELETE FROM courses WHERE department = 'Computer Science' AND code IN (
  'CSC 100', 'COS 203', 'COS 204', 'COS 205', 'COS 206', 'COS 207', 'COS 208',
  'CSC 227', 'STA 201',
  'COS 301', 'COS 302', 'COS 303', 'COS 304', 'COS 305', 'COS 306', 'COS 307', 'COS 308', 'COS 309', 'COS 310', 'COS 399',
  'COS 401', 'COS 402', 'COS 403', 'COS 404', 'COS 405', 'COS 406', 'COS 407', 'COS 408', 'COS 410', 'COS 498', 'COS 499'
);

-- Step 2: Update existing courses that have wrong data
-- Fix PHY 101 units (3 -> 2)
UPDATE courses SET units = 2, description = 'Mechanics: Space and time, vectors and scalars, kinematics, Newton''s laws of motion, conservation principles, rotational motion, gravitation.', overview = 'Space and time; units and dimension, Vectors and Scalars, Differentiation of vectors: displacement, velocity and acceleration; kinematics; Newton laws of motion; Relative motion; Conservation principles in physics; Rotational motion; Gravitation: Newton''s Law of Gravitation, Kepler''s Laws.' WHERE code = 'PHY 101' AND department = 'Computer Science';

-- Fix PHY 102 units (3 -> 2)
UPDATE courses SET units = 2, code = 'PHY 102', description = 'Electricity & Magnetism: Electrostatics, Coulomb''s law, Gauss''s law, capacitance, DC circuits, magnetic fields, electromagnetic induction, Maxwell''s equations, AC circuits.', overview = 'Forces in nature. Electrostatics. Coulomb''s law and superposition. Electric field and potential. Gauss''s law. Capacitance. DC circuits. Magnetic fields. Electromagnetic induction. Maxwell''s equations. AC voltages and currents.' WHERE code = 'PHY 102' AND department = 'Computer Science';

-- Fix GST 212 semester (First -> Second) 
UPDATE courses SET semester = 'Second', description = 'Philosophy, Logic and Human Existence: branches of philosophy, logic, syllogism, symbolic logic, informal fallacies, valid and invalid arguments, critical thinking.', overview = 'Notions, meanings, branches and problems of philosophy. Logic as an indispensable tool of philosophy. Elements of syllogism, symbolic logic. Informal fallacies, laws of thought. Valid and invalid arguments. Creative and critical thinking. Impact of philosophy on human existence.' WHERE code = 'GST 212' AND department = 'Computer Science';

-- Fix ENT 211 (make sure it's in correct semester)
UPDATE courses SET semester = 'First', level = '200', description = 'Entrepreneurship and Innovation: concepts, theories, characteristics of entrepreneurs, entrepreneurial thinking, innovation, enterprise formation, e-commerce.', overview = 'Concept of Entrepreneurship. Theories, Rationale and relevance. Characteristics of Entrepreneurs. Entrepreneurial thinking. Innovation. Enterprise formation, partnership and networking. Contemporary Entrepreneurship Issues. Basic principles of e-commerce.' WHERE code = 'ENT 211' AND department = 'Computer Science';

-- Update COS 101 description from handbook
UPDATE courses SET description = 'Introduction to computing: basic components, applications, information processing, the Internet, computing discipline areas and specializations.', overview = 'Brief history of computing. Description of basic components of a computer. Input/Output devices. Hardware, software and human ware. Computer applications. Information processing and its roles in society. The Internet and its applications. Different areas of the computing discipline. Job specializations for computing professionals.' WHERE code = 'COS 101' AND department = 'Computer Science';

-- Update COS 102
UPDATE courses SET description = 'Problem solving processes and skills, algorithms, flowcharts, pseudocode, and programming in C/Python.', overview = 'Introduction to core concepts of computing. Problems and problem-solving. Method of solving computing problems. Solvable and unsolvable problems. Solution techniques. General problem-solving process. Solution formulation: flowchart, pseudocode, decision table. Implementation and refinement. Programming in C, Python.' WHERE code = 'COS 102' AND department = 'Computer Science';

-- Update COS 201
UPDATE courses SET description = 'Principles of programming: structured programming, OOP concepts, data types, control structures, arrays, recursion, inheritance, polymorphism.', overview = 'Essentials of computer programming. Types of programming. Scripting languages. Structured programming principles. Basic data types, variables, expressions. Basic OOP concepts: abstraction, objects, classes, methods, encapsulation. Class hierarchies. Searching, sorting, recursive algorithms. Event-driven programming. Strings and I/O.' WHERE code = 'COS 201' AND department = 'Computer Science';

-- Update COS 202
UPDATE courses SET description = 'Advanced OOP: polymorphism, abstract classes, interfaces, API usage, searching, sorting, recursion, event-driven and GUI programming.', overview = 'Review of advanced OOP - polymorphism, abstract classes and interfaces. Class hierarchies using packages/namespaces. API usage. Searching, sorting, recursive algorithms. Event-driven programming. Exception handling. GUI programming.' WHERE code = 'COS 202' AND department = 'Computer Science';

-- Update COS 409
UPDATE courses SET units = 3, description = 'Research methodology: types, approaches, data collection methods, questionnaire design, report writing, sampling design, data analysis.', overview = 'Foundations of Research. Types and approaches. Research Methods vs Methodology. Research Process. Scientific investigation. Problem formulation. Data Collection methods. Guidelines for constructing questionnaires. Research Proposal and Plan. Technical Report Writing. Sampling Design. Data Analysis.' WHERE code = 'COS 409' AND department = 'Computer Science';

-- Step 3: Insert all missing courses from CCMAS 2025-2026 Handbook

-- 100L First Semester (missing)
INSERT INTO courses (code, title, level, semester, units, department, status, description, overview) VALUES
('GST 111', 'Communication in English', '100', 'First', 2, 'Computer Science', 'C', 'English language skills: sound patterns, word classes, sentence types, grammar, logical thinking, writing activities, comprehension strategies.', 'Sound patterns in English Language. English word classes. Sentence in English. Grammar and Usage. Logical and Critical Thinking. Writing Activities. Comprehension Strategies. Information and Communication Technology in modern Language Learning.'),
('MTH 101', 'Elementary Mathematics I', '100', 'First', 2, 'Computer Science', 'C', 'Algebra and Trigonometry: set theory, real numbers, sequences, quadratic equations, binomial theorem, complex numbers, trigonometric functions.', 'Elementary set theory, subsets, union, intersection, complements, Venn diagrams. Real numbers. Mathematical induction. Real sequences and series. Theory of quadratic equations. Binomial theorem. Complex numbers. De-Moivre''s theorem. Trigonometric functions.'),
('STA 111', 'Descriptive Statistics', '100', 'First', 3, 'Computer Science', 'C', 'Statistical data types, sources, collection methods, presentation, frequency distributions, measures of location, dispersion, skewness, index numbers.', 'Statistical data. Types, sources and methods of collection. Presentation of data. Errors and approximations. Frequency and cumulative distributions. Measures of location, partition, dispersion, skewness and Kurtosis. Rates, ratios and index numbers.'),
('LAG-CSC 103', 'Fundamental of Programming', '100', 'First', 3, 'Computer Science', 'C', 'Programming fundamentals: languages, program development cycle, data types, operators, control structures, arrays, functions, preprocessor directives.', 'Types of Programming languages. Program development cycle. Structure of a program. Compilation and Execution. Data types, constants, variables. Operators and Expressions. Conditional Statements and Loops. Subprograms. Storage classes. Arrays and Strings.'),
('LAG-CYB 105', 'Introduction to Data Analysis with Statistical Packages', '100', 'First', 2, 'Computer Science', 'E', 'Hands-on training in SPSS, MATLAB, STATISTICA for statistical analysis, data manipulation, and interpretation of research results.', 'The SPSS environment. Data entry and editing. Histograms, boxplots, bar charts, scatterplots. Correlation analysis. Regression analysis. ANOVA. Non-parametric tests. Use of statistical packages like SPSS, SAS, Minitab.')
ON CONFLICT DO NOTHING;

-- 100L Second Semester (missing)
INSERT INTO courses (code, title, level, semester, units, department, status, description, overview) VALUES
('GST 112', 'Nigerian Peoples and Culture', '100', 'Second', 2, 'Computer Science', 'C', 'Nigerian history, culture, political evolution, trade and economics, social justice, norms and values, re-orientation strategies.', 'Nigerian history, culture and art up to 1800. Nigeria under colonial rule. Evolution of Nigeria as a political unit. Challenges of nation-building. Trade and economics of self-reliance. Social justice. Individual norms and values. Re-orientation and national values.'),
('MTH 102', 'Elementary Mathematics II', '100', 'Second', 2, 'Computer Science', 'C', 'Calculus: functions, limits, continuity, differentiation techniques, curve sketching, integration methods, definite integrals, areas and volumes.', 'Function of a real variable, graphs, limits and continuity. The derivative as limit of rate of change. Techniques of differentiation. Extreme curve sketching. Integration as inverse of differentiation. Methods of integration. Definite integrals. Application to areas, volumes.'),
('LAG-CSC 104', 'Introduction to Web Design and Development', '100', 'Second', 3, 'Computer Science', 'C', 'Web design fundamentals: HTML, CSS, JavaScript, responsive design, web development tools and best practices.', 'Introduction to web technologies. HTML structure and semantics. CSS styling and layout. JavaScript fundamentals. Responsive web design. Web development tools. Building interactive web pages. Web hosting and deployment.'),
('LAG-CYB 106', 'Basic Theory and Principles of Computer Security', '100', 'Second', 3, 'Computer Science', 'E', 'Computer security concepts: threats, attacks, cryptography, access control, malicious software, firewalls, network security, privacy.', 'Introduction to computer security. Threats, Attacks, and Assets. User Authentication. Access Control. Malicious Software. Intrusion Detection. Firewalls. Cryptographic Algorithms. Network and Web Security. Database Security. Legal and Ethical Aspects.'),
('LAG-CSC 106', 'Introduction to Algorithms and Data Structures', '100', 'Second', 3, 'Computer Science', 'C', 'Data structures (arrays, stacks, queues, linked lists, trees, graphs), searching and sorting algorithms, algorithm analysis.', 'Data Management concepts. Linear Data Structures: Arrays, Stacks, Queues, Linked Lists. Nonlinear Data Structures: Trees (binary search trees, AVL trees), Graphs (BFS, DFS, spanning trees, shortest path). Sorting: Insertion, Quick, Merge, Heap Sort. Searching: Linear, Binary Search.')
ON CONFLICT DO NOTHING;

-- 200L First Semester (missing)
INSERT INTO courses (code, title, level, semester, units, department, status, description, overview) VALUES
('MTH 201', 'Mathematical Methods I', '200', 'First', 2, 'Computer Science', 'C', 'Real-valued functions, Mean Value Theorem, Taylor Series expansion, Line Integrals, Surface Integrals, Volume Integrals.', 'Real-valued functions of a real variable. Mean Value Theorem. Taylor Series expansion. Line Integrals. Surface Integrals. Volume Integrals.'),
('CSC 203', 'Discrete Structures', '200', 'First', 2, 'Computer Science', 'C', 'Propositional and predicate logic, sets, functions, proof techniques, mathematical induction, combinatorics, discrete probability, recurrence relations.', 'Propositional Logic. Predicate Logic. Sets. Functions. Sequences and Summation. Proof Techniques. Mathematical induction. Inclusion-exclusion and Pigeonhole principles. Permutations and Combinations. Binomial Theorem. Discrete Probability. Recurrence Relations.'),
('IFT 211', 'Digital Logic Design', '200', 'First', 2, 'Computer Science', 'C', 'Information representation, number systems, Boolean algebra, combinational and sequential circuit design, flip-flops, registers, counters.', 'Information representation and number systems. Boolean algebra and switching theory. Combinational circuits design using multiplexers, decoders, comparators and adders. Sequential circuit analysis and design. Flip-flops, registers, counters, RAMs, ROMs, PLAs, FPGAs.'),
('SEN 201', 'Introduction to Software Engineering', '200', 'First', 2, 'Computer Science', 'C', 'Software lifecycle, requirements analysis, design, development, testing, maintenance, UML, software project management.', 'Software Engineering concepts and principles. Software processes and lifecycle models. Software requirements and specifications. Software design and architecture. Software metrics, quality and testing. Software validation and evolution. Software project management.'),
('LAG-CSC 205', 'Introduction to Computational Methods', '200', 'First', 3, 'Computer Science', 'C', 'Numerical methods: root finding, linear systems, interpolation, numerical differentiation and integration, curve fitting.', 'Binary Numbers and Error Analysis. Solution of Nonlinear Equations: Bisection, False Position, Newton-Raphson Method. Solution of Linear Systems: Gaussian Elimination, LU Factorization, Iterative Methods. Numerical Differentiation and Integration. Interpolation: Lagrange, Newton Polynomial. Curve Fitting.'),
('DTS 201', 'Introduction to Data Science', '200', 'First', 2, 'Computer Science', 'E', 'Fundamentals of Data Science: methodology, data classification, data science process, visualization, predictions, models, and applications.', 'Fundamentals of Data Science. Basic classification of Data. Steps of Data Science Process: collection, pre-processing, training, testing. Data visualizations. Distributions, Probability, Simulations. Predictions and Models. Data mining, Business Intelligence, Big Data, Data Analytics.'),
('ICT 201', 'Introduction to Information and Communication Technologies', '200', 'First', 2, 'Computer Science', 'E', 'Computer principles, data transmission, memory, I/O devices, software types, network types, Internet, office applications.', 'Basic principle of computers. Data transmission. RAM and permanent memory. Graphic processing. Communication Ports. Software types. Network Types. Internet. Office Applications. Telecommuting.')
ON CONFLICT DO NOTHING;

-- 200L Second Semester (missing)
INSERT INTO courses (code, title, level, semester, units, department, status, description, overview) VALUES
('MTH 202', 'Elementary Differential Equations', '200', 'Second', 2, 'Computer Science', 'C', 'Derivation of differential equations, first and second order equations, systems of equations, finite difference equations, applications.', 'Derivation of differential equations from primitive, geometry, physics. Order and degree. Techniques for solving first and second order linear and non-linear equations. Systems of first order linear equations. Finite linear difference equations. Application to geometry and physics.'),
('IFT 212', 'Computer Architecture and Organisation', '200', 'Second', 2, 'Computer Science', 'C', 'CPU organization, instruction set architecture, assembly language, datapath and control unit, memory hierarchy, cache, virtual memory, I/O.', 'Principles of computer hardware and instruction set architecture. Internal CPU organisation. Instruction format and types. Dataflow, arithmetic, flow control instructions. Data path and control unit design. Assembly language programming. Memory hierarchy. Cache and virtual memory. I/O organisations.'),
('CSC 299', 'SIWES I', '200', 'Second', 3, 'Computer Science', 'C', 'Industrial training attachment for practical experience in computing, supervised by faculty.', 'Students are attached to private and public organisations for three months to acquire practical experience in Computer Science. Students are supervised and must submit a report on knowledge acquired and experience gained.'),
('LAG-CSC 224', 'Introduction to Information Processing', '200', 'Second', 3, 'Computer Science', 'E', 'Information systems, management information systems, data communication, sorting and searching, data security.', 'Information Systems. Management Information Systems. Information Processing. Information Systems Output and Storage. Data Security and Control. Sorting and searching. Principles of Data Communication. Computer Networks. OSI Model. Internet Services.'),
('INS 202', 'Human-Computer Interface', '200', 'Second', 2, 'Computer Science', 'E', 'HCI foundations, GUI design principles, user conceptual models, ergonomics, human-centred evaluation.', 'Foundations of HCI. Concept underlying the design of HCI. Principles of GUI. GUI toolkits. System design methods. User conceptual models and interface metaphors. Human cognitive and physical ergonomics. Human-centred software evaluation. GUI design and programming.'),
('INS 204', 'Systems Analysis and Design', '200', 'Second', 3, 'Computer Science', 'C', 'Structured analysis and design of information systems: SDLC, dataflow diagrams, entity-relationship modelling, prototyping, database design.', 'Structured approach to analysis and design of information systems. Software development life cycle. Dataflow diagramming. Entity relationship modelling. Computer aided software engineering. Input/output prototyping. File and database design. User interface design.'),
('DTS 204', 'Statistical Computing Inference and Modelling', '200', 'Second', 3, 'Computer Science', 'E', 'Statistical models, sampling distributions, hypothesis testing, regression, correlation, programming in Python, use of statistical packages.', 'Population and samples. Statistical models and methodologies. Random sampling distributions. Time series analysis. Estimation and tests of hypotheses. Regression and correlation. Programming in Python. Computation of mean, variance, correlation. Use of SPSS, SAS, Minitab.'),
('LAG-CSC 210', 'Concurrent Programming', '200', 'Second', 2, 'Computer Science', 'E', 'Concurrency foundations, shared memory, message passing, concurrent program design, performance and safety analysis.', 'Shared Memory. Consistency. Message passing - point-to-point versus multicast. Blocking. Concurrency fundamentals. Concurrent programming in C, Java. Performance evaluation, scalability analysis. Safety and liveness properties.')
ON CONFLICT DO NOTHING;

-- 300L First Semester (missing)
INSERT INTO courses (code, title, level, semester, units, department, status, description, overview) VALUES
('CSC 301', 'Data Structures', '300', 'First', 3, 'Computer Science', 'C', 'Advanced data structures: arrays, records, strings, stacks, queues, trees, linked structures, pointers, memory management.', 'Primitive types, Arrays, Records, Strings and String processing. Data representation in memory. Stack and Heap allocation. Queues, Trees. Implementation strategies for stacks, queues, trees. Run time storage management. Pointers and References, linked structures.'),
('CSC 309', 'Artificial Intelligence', '300', 'First', 2, 'Computer Science', 'C', 'AI fundamentals: intelligent agents, search algorithms, knowledge representation, NLP, expert systems, programming for AI.', 'Overview of AI. History, goals, types, techniques, branches. Intelligent Agents. Search algorithms and strategies. Knowledge Representation: semantic networks, frames. Natural Language Processing. Expert Systems. Programming Languages for AI.'),
('CYB 201', 'Introduction to Cybersecurity and Strategy', '300', 'First', 2, 'Computer Science', 'C', 'Cybersecurity concepts, threats, attacks, defence strategies, cryptography, intrusion detection, policies and guidelines.', 'Basic concepts: confidentiality, integrity, availability, authentication. Security policies. Risk management. Cryptography. Network security. Intrusion detection systems. Cyber-attacks evolution. Cybersecurity policy and guidelines. Impact on civil, military, business institutions.'),
('ICT 305', 'Data Communication System and Network', '300', 'First', 3, 'Computer Science', 'C', 'Data transmission, network architectures, OSI model, internet technologies, protocols, LAN/WAN, error detection and correction.', 'Data transmission over layered networks. Internet technologies and protocols. OSI model. Local Area Networks. Metropolitan Area Networks. Error Detection and Correction techniques. Network Operating Systems.'),
('LAG-CSC 315', 'Introduction to Machine and Assembly Languages', '300', 'First', 3, 'Computer Science', 'E', 'Assembly language fundamentals: processor architectures, registers, addressing modes, subroutines, stack operations, debugging.', 'General introduction to Assembly and Machine language. Processor architectures. Intel 8088 registers. Data declarations. Number conversions. MASM/TASM. Assembly arithmetic. Branching instructions. Subroutines. Stack operations. Strings and arrays. High-level language interface.'),
('LAG-CSC 331', 'Real-Time Systems and Programming', '300', 'First', 3, 'Computer Science', 'E', 'Real-time systems concepts, embedded systems, RTOS, scheduling, concurrency, hardware fundamentals, practical applications with Arduino/Raspberry Pi.', 'Introduction to Real-Time Systems. Embedded real-time systems. Real-time operating systems. Software Life Cycle for ERT. Concurrency. Scheduling. Control of shared resources. Inter-task communication. Memory management. Hardware fundamentals. Arduino and Raspberry Pi applications.')
ON CONFLICT DO NOTHING;

-- 300L Second Semester (missing)
INSERT INTO courses (code, title, level, semester, units, department, status, description, overview) VALUES
('GST 312', 'Peace and Conflict Resolution', '300', 'Second', 2, 'Computer Science', 'C', 'Concepts of peace, conflict, security, types and causes of conflicts, peace building strategies, roles of international organisations.', 'Concepts of Peace, Conflict, and Security. Types and Theories of Conflicts. Root causes of Conflict and Violence in Africa. Peace Building and Conflict Management. Justice and Legal framework. Insurgency and Terrorism. Peace Mediation. Alternative Dispute Resolution. Roles of International Organisations.'),
('ENT 312', 'Venture Creation', '300', 'Second', 2, 'Computer Science', 'C', 'Venture creation: opportunity identification, business planning, entrepreneurial finance, marketing, e-commerce, small business management.', 'Opportunity Identification. New business development. Entrepreneurial finance. Entrepreneurial marketing and e-commerce. Small business management. Negotiation and business communication. AI, VR, IoT, Blockchain in business.'),
('CSC 308', 'Operating Systems', '300', 'Second', 3, 'Computer Science', 'C', 'OS fundamentals: process management, CPU scheduling, memory management, virtual memory, file systems, I/O, security, distributed systems.', 'History and evolution of operating systems. Types and structures. Process management: processes, threads, CPU scheduling, synchronisation. Memory management and virtual memory. File systems. I/O systems. Security and protection. Distributed systems.'),
('CSC 322', 'Computer Science Innovation and New Technologies', '300', 'Second', 2, 'Computer Science', 'C', 'Innovation concepts, product development, digital marketing, entrepreneurial opportunities in IT, business planning and ethics.', 'Fundamental concepts of innovation. Product development. Business leadership. Digital marketing. Entrepreneurial opportunities in IT. Legal issues and Business ethics. New venture creation. Business feasibility. Market research. Business models and plans.'),
('DTS 304', 'Data Management I', '300', 'Second', 3, 'Computer Science', 'C', 'Database systems: components, relational models, SQL, database design, normalisation, security, concurrency, query optimisation.', 'Information Management Concepts. Database systems components. DBMS functions. Database architecture. Relational data models. Semi-structured data models. Database Design. Database security and integrity. Query processing and optimisation. Concurrency and recovery.'),
('CSC 399', 'SIWES II', '300', 'Second', 3, 'Computer Science', 'C', 'Second industrial training attachment for advanced practical experience in computing.', 'Students are attached to private and public organisations for three months to acquire advanced practical experience in Computer Science. Students submit a comprehensive report and defend their reports.'),
('LAG-ISR 302', 'Information and Knowledge Management', '300', 'Second', 2, 'Computer Science', 'E', 'Content management, digital representations, knowledge extraction, data mining, information retrieval, ontologies.', 'Content management models, frameworks, systems. Digital representations of content. Digital content creation, capture and preservation. Content structure and management. Processing and pattern recognition. Indexing, searching, retrieving. Knowledge management, ontologies.'),
('LAG-CSC 326', 'Introduction to Compiler Construction', '300', 'Second', 3, 'Computer Science', 'C', 'Compiler structure: lexical analysis, syntax analysis, semantic analysis, code generation, error handling, optimisation.', 'Overview of Compilers. Lexical Analyzer: tokens, lexemes, patterns. Finite automata. Symbol Table organization. Syntax analysis: parsing, grammar classes, top-down and bottom-up parsing. Intermediate Code Generation. Code Optimization. Code Generation.'),
('LAG-CSC 328', 'Introduction to Theory of Computing', '300', 'Second', 3, 'Computer Science', 'C', 'Formal languages: Chomsky hierarchy, regular expressions, finite automata, context-free grammars, push-down automata, Turing machines.', 'Models of Computer languages. Chomsky hierarchy of grammars. Regular grammar and expressions. Deterministic and Non-Deterministic Finite Automata. Context-free grammar. Push-Down Automata. Context-sensitive grammar. Turing Machines. Computational complexity, NP Completeness.')
ON CONFLICT DO NOTHING;

-- 400L First Semester (missing)
INSERT INTO courses (code, title, level, semester, units, department, status, description, overview) VALUES
('COS 401', 'Algorithm and Complexity Analysis', '400', 'First', 2, 'Computer Science', 'C', 'Algorithm analysis: asymptotic notation, complexity classes, algorithmic strategies (greedy, divide-and-conquer, dynamic programming), searching and sorting.', 'Basic algorithmic analysis. Asymptotic analysis. Standard Complexity Classes. Time and space trade-offs. Recursive algorithms. Algorithmic Strategies. Fundamental computing algorithms. Numerical algorithms. Search and sort algorithms. Binary Search trees. Hash tables. Graphs.'),
('CSC 497', 'Final Year Project I', '400', 'First', 3, 'Computer Science', 'C', 'Independent research project: topic identification, literature review, methodology design, proposal writing and presentation.', 'An independent investigation of software, hardware, communication or IT related problems in Computer Science. Literature review. Research methodology. Written proposal with outline, schedule, and resource needs. Oral presentation required.'),
('INS 401', 'Project Management', '400', 'First', 2, 'Computer Science', 'C', 'Project management lifecycle, team management, scheduling, resource management, procurement, risk management, quality assurance.', 'Introduction to Project Management. Project Management Lifecycle. Managing Project Teams. Project communication. Project Initiation and Planning. Managing Scope, Scheduling, Resources. Project quality. Risk management. Procurement. Project Execution, Control and Closure.'),
('LAG-CSC 405', 'Numerical Computation', '400', 'First', 3, 'Computer Science', 'E', 'Advanced numerical methods: floating-point arithmetic, linear programming, optimisation, root finding, differential equations, machine learning introduction.', 'Numerical computation approaches. Numerical errors. Floating-point arithmetic. Linear programming. Nonlinear optimization. Root finding. Interpolation and approximation. Numerical integration and differentiation. Ordinary and partial differential equations. Introduction to Machine learning.'),
('LAG-CSC 407', 'Entrepreneurship and Business Development for Computer Scientists', '400', 'First', 2, 'Computer Science', 'C', 'Entrepreneurship overview, developing technical ideas into business opportunities, market research, go-to-market strategies, team management.', 'Overview of entrepreneurship. Developing technical ideas into business opportunities. Market research. Go-to-market strategies. Value propositions. Team management. Project management tools. Cost/benefit analysis. Sustainable design. Environmental impacts of computing.'),
('LAG-CSC 413', 'Compiler Design and Construction', '400', 'First', 3, 'Computer Science', 'E', 'Advanced compiler topics: architecture, register allocation, optimization, interpreters, virtual machines, runtime environments, garbage collection.', 'Programs that take programs as input. Abstract syntax trees. Translation and compilation. Interpretation vs compilation. Language translation pipeline. Runtime representation. Memory management. Scanning using regular expressions. Parsing strategies. Code optimization. Register allocation.'),
('LAG-CSC 417', 'Machine Learning', '400', 'First', 3, 'Computer Science', 'C', 'Machine learning fundamentals: classification, supervised and unsupervised learning, decision trees, Naive Bayes, model evaluation.', 'Definition and examples of machine learning tasks. Inductive learning. Naive Bayesian Classifier. Decision trees. Over-fitting problem. Measuring classifier accuracy. Parameter estimation. Supervised learning. Unsupervised learning. Statistical techniques for classification.'),
('LAG-CSC 419', 'Modelling and Simulation', '400', 'First', 3, 'Computer Science', 'E', 'Modelling methods: agent-based, system dynamics, discrete event simulation, queuing theory, Monte Carlo simulation, optimization.', 'Basic Modelling and Simulation concepts. Random Number generation. Agent-based modeling. System dynamics. Discrete event simulation. Queuing theory. Monte Carlo simulation. Model validation and verification. Markov and Hidden Markov Chain. Optimization and control.'),
('LAG-CSC 421', 'Principles of Programming Language', '400', 'First', 3, 'Computer Science', 'C', 'Programming language theory: syntax, semantics, types, memory management, OOP, functional and logic programming, language implementation.', 'Introduction and History of programming languages. Program structure. Data types, abstraction, polymorphism. Memory Allocation. Object-oriented programming. Syntax. Values and types. Scopes and Bindings. Runtime Environments. Functional Programming. Logic Programming. Various languages: LISP, Prolog, ML, Java.'),
('LAG-CSC 423', 'System Performance Evaluation', '400', 'First', 3, 'Computer Science', 'E', 'Performance modelling, discrete event simulation, queuing theory, workload characterization, capacity planning, performance bottleneck identification.', 'Basic techniques of system performance evaluation. Performance modelling. Discrete event simulation. Verification and validation. Analysis of queuing networks. System tuning. Workload characterization. Capacity planning. Queuing theory. Mean value analysis.'),
('LAG-CSC 425', 'Advanced Operating Systems', '400', 'First', 3, 'Computer Science', 'E', 'Distributed systems architectures, process synchronization, distributed file systems, fault tolerance, client-server model, real-time distributed systems.', 'Advanced process synchronization. Distributed systems architectures. Distributed file systems. Distributed resource management. Fault tolerance and Recovery. Client-server model. Remote procedure call. Clock synchronization. Mutual exclusion. Deadlock in distributed systems.'),
('LAG-CSC 427', 'Introduction to Telemedicine and e-Health', '400', 'First', 3, 'Computer Science', 'E', 'Telemedicine concepts, healthcare informatics, mobile telehealth, DICOM, PACS, hospital information systems, medical image annotation.', 'Introduction to Telemedicine and e-health. Administrative Standards. Telemedicine Terminology. Informatics. Mobile Telehealth. Tele radiology and PACS. DICOM. Hospital information management system. Remote Nursing. Drug usage management. Ontology development.')
ON CONFLICT DO NOTHING;

-- 400L Second Semester (missing)
INSERT INTO courses (code, title, level, semester, units, department, status, description, overview) VALUES
('CSC 402', 'Ethics and Legal Issues in Computer Science', '400', 'Second', 2, 'Computer Science', 'C', 'Social, ethical, legal and managerial issues in computing: privacy, security, software reliability, intellectual property, professional responsibility.', 'Social, ethical, legal and managerial issues in computing. Computer security. Privacy. Software reliability. Personal responsibility. Intellectual property. Environment and health concerns. Fairness in the workplace. Case studies.'),
('CSC 498', 'Final Year Project II', '400', 'Second', 3, 'Computer Science', 'C', 'Continuation of CSC 497: implementation, evaluation, written report (chapters 4-5), final submission and oral presentation.', 'Continuation of CSC 497. Implementation and evaluation of the project. Final written report. Oral presentation and defence.'),
('LAG-CSC 416', 'Financial Software Projects', '400', 'Second', 3, 'Computer Science', 'E', 'Fintech software development: blockchain, DevOps, cybersecurity, risk assessment, financial software design and entrepreneurship.', 'Overview of the financial market. Commercial banks and Fintech companies. Role of software engineers in finance. Software engineering principles. Risk assessment tools and techniques. Risk management frameworks. Financial software projects. Testing and maintenance.'),
('LAG-CSC 418', 'Computer Graphics and Animation', '400', 'Second', 3, 'Computer Science', 'E', 'Graphics pipeline, 2D/3D rendering, OpenGL, ray tracing, shading, curves, surfaces, 3D modelling, animation techniques.', 'Graphics pipeline and display technologies. 2D drawing algorithms. OpenGL API. Clipping and transformations. Projection and hidden surface removal. Ray tracing. Shading and shadows. Curves and surfaces. 3D modelling. Animation techniques. Texture mapping.'),
('LAG-CSC 420', 'Advanced Data Structures', '400', 'Second', 3, 'Computer Science', 'E', 'Advanced data structures: hashing, priority queues, heaps, AVL trees, B-Trees, Red-Black trees, graph algorithms, disjoint sets, string matching.', 'Hashing: hash functions, collision resolution. Priority Queues and Heaps. Binary Heap operations. Binomial Queues. AVL Trees, B-Trees, Red-Black Trees. Graph Algorithms: topological sort, Dijkstra, Bellman-Ford, Floyd-Warshall. Disjoint Sets. String Matching: Rabin-Karp, KMP.'),
('LAG-CSC 422', 'Computer Networks', '400', 'Second', 3, 'Computer Science', 'E', 'Internet organization, switching, layering, routing, TCP/UDP, HTTP, DNS, IP addressing, LAN/Ethernet, congestion control.', 'Organization of the Internet. Switching techniques. Physical network pieces. Layering principles. Naming and address schemes (DNS, IP). Distributed applications. HTTP. TCP and UDP. Socket APIs. Routing. Local Area Networks. Ethernet. Congestion control.'),
('LAG-CSC 424', 'Computer Architecture', '400', 'Second', 3, 'Computer Science', 'E', 'Computer organization, arithmetic, CPU design, memory systems, cache, I/O, bus structures, parallel architectures, hardware security.', 'Computer Organization vs Architecture. Microprocessor architecture. Interrupts. Bus Interconnection. Cache Memory. Semiconductor Memories. RAID. I/O systems. DMA. Operating System overview. Arithmetic Logic Unit. Binary representation. Floating-Point representation.'),
('LAG-CSC 426', 'Optimization Techniques', '400', 'Second', 3, 'Computer Science', 'E', 'Linear programming, transportation and assignment problems, sequencing, game theory, inventory models, dynamic programming, queuing theory, simulation.', 'Linear programming: graphical, simplex methods. Transportation and assignment problems. Sequencing techniques. Game theory. Inventory control models. Dynamic programming: shortest path. Queuing systems. Simulation: types, process, applications.')
ON CONFLICT DO NOTHING;
